package br.ufrn.sigaa.monitoria.dominio;

// Generated 09/10/2006 10:44:38 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ufrn.arq.dominio.PersistDB;

/*******************************************************************************
 * SolicitacaoRenovacao generated by hbm2java
 * <p>
 * Representa uma solicitação de renovação de projeto de ensino de monitoria.
 * Atualmente esta solicitação está sendo feita via relatório parcial de
 * projeto.
 * </p>
 * 
 ******************************************************************************/
@Entity
@Table(name = "solicitacao_renovacao", schema = "monitoria")
public class SolicitacaoRenovacao implements PersistDB {

	// Fields

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id_solicitacao_renovacao")
	private int id;

	@Temporal(TemporalType.DATE)
	@Column(name = "data")
	private Date data;

	@ManyToOne
	@JoinColumn(name = "id_projeto_monitoria")
	private ProjetoEnsino projetoEnsino;

	@Column(name = "descricao")
	private String descricao;

	@ManyToOne
	@JoinColumn(name = "id_status_renovacao")
	private StatusSolicitacaoRenovacao status;

	// Constructors

	/** default constructor */
	public SolicitacaoRenovacao() {
	}

	/** minimal constructor */
	public SolicitacaoRenovacao(int idSolicitacaoRenovacao, Date data,
			ProjetoEnsino projetoEnsino) {
		this.id = idSolicitacaoRenovacao;
		this.data = data;
		this.projetoEnsino = projetoEnsino;
	}

	/** full constructor */
	public SolicitacaoRenovacao(int idSolicitacaoRenovacao, Date data,
			ProjetoEnsino projetoEnsino, String descricao) {
		this.id = idSolicitacaoRenovacao;
		this.data = data;
		this.projetoEnsino = projetoEnsino;
		this.descricao = descricao;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int idSolicitacaoRenovacao) {
		this.id = idSolicitacaoRenovacao;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public ProjetoEnsino getProjetoEnsino() {
		return this.projetoEnsino;
	}

	public void setProjetoEnsino(ProjetoEnsino projetoEnsino) {
		this.projetoEnsino = projetoEnsino;
	}

	
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	/**
	 * @return the status
	 */
	
	public StatusSolicitacaoRenovacao getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(StatusSolicitacaoRenovacao status) {
		this.status = status;
	}

}
