/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '13/09/2006'
 *
 */
package br.ufrn.sigaa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnidadesRh generated by hbm2java
 */
@Entity
@Table(name = "unidades_rh", schema = "rh", uniqueConstraints = {})
public class UnidadesRh {

	// Fields    

	private String uorg;

	private String sigla;

	private String descricao;

	// Constructors

	/** default constructor */
	public UnidadesRh() {
	}

	/** minimal constructor */
	public UnidadesRh(String uorg, String descricao) {
		this.uorg = uorg;
		this.descricao = descricao;
	}

	/** full constructor */
	public UnidadesRh(String uorg, String sigla, String descricao) {
		this.uorg = uorg;
		this.sigla = sigla;
		this.descricao = descricao;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "uorg", unique = true, nullable = false, insertable = true, updatable = true, length = 12)
	public String getUorg() {
		return this.uorg;
	}

	public void setUorg(String uorg) {
		this.uorg = uorg;
	}

	@Column(name = "sigla", unique = false, nullable = true, insertable = true, updatable = true, length = 10)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "descricao", unique = false, nullable = false, insertable = true, updatable = true, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
