/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '13/09/2006'
 *
 */
package br.ufrn.sigaa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;

/**
 * UsuarioUnidade generated by hbm2java
 */
@Entity
@Table(name = "usuario_unidade", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"id_usuario", "id_unidade" }) })
public class UsuarioUnidade implements PersistDB {

	// Fields    

	private int id;

	private Unidade unidade;

	private Usuario usuario;

	private Usuario usuarioCadastro;

	private Date data;

	// Constructors

	/** default constructor */
	public UsuarioUnidade() {
	}

	/** default minimal constructor */
	public UsuarioUnidade(int id) {
		this.id = id;
	}
	
	/** minimal constructor */
	public UsuarioUnidade(int idUsuarioUnidade, Unidade unidadeByIdUnidade,
			Usuario usuario) {
		this.id = idUsuarioUnidade;
		this.unidade = unidadeByIdUnidade;
		this.usuario = usuario;
	}

	/** full constructor */
	public UsuarioUnidade(int idUsuarioUnidade, Unidade unidadeByIdUnidade,
			Unidade unidadeByIdSetor, Usuario usuario,
			Usuario usuarioCadastro, Date data) {
		this.id = idUsuarioUnidade;
		this.unidade = unidadeByIdUnidade;
		this.usuario = usuario;
		this.usuarioCadastro = usuarioCadastro;
		this.data = data;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_usuario_unidade", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idUsuarioUnidade) {
		this.id = idUsuarioUnidade;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidade", unique = false, nullable = false, insertable = true, updatable = true)
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidadeByIdUnidade) {
		this.unidade = unidadeByIdUnidade;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", unique = false, nullable = false, insertable = true, updatable = true)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_cadastro", unique = false, nullable = false, insertable = true, updatable = true)
	public Usuario getUsuarioCadastro() {
		return this.usuarioCadastro;
	}

	public void setUsuarioCadastro(Usuario usuarioCadastro) {
		this.usuarioCadastro = usuarioCadastro;
	}

	@Column(name = "data", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id");
	}
	
	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id);
	}

}
