package br.ufrn.sigaa.ensino.tecnico.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.sigaa.ensino.dominio.ComponenteCurricular;

/**
 * Relacionamento entre MODULO  e DISCIPLINA.
 *
 * ModuloDisciplina generated by hbm2java
 */
@Entity
@Table(name = "modulo_disciplina", schema = "tecnico", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"id_modulo", "id_disciplina" }) })
public class ModuloDisciplina implements PersistDB {

	/** Chave primária. */
	private int id;

	/** Indica o Módulo associado. */
	private Modulo modulo;

	/** Indica o Componente Curricular associado. */
	private ComponenteCurricular disciplina;

	// Constructors

	/** default constructor */
	public ModuloDisciplina() {
	}

	/** default minimal constructor */
	public ModuloDisciplina(int id) {
		this.id = id;
	}

	/** full constructor */
	public ModuloDisciplina(int idModuloDisciplina, Modulo modulo,
			ComponenteCurricular disciplina) {
		this.id = idModuloDisciplina;
		this.modulo = modulo;
		this.disciplina = disciplina;
	}

	public ModuloDisciplina(ComponenteCurricular disciplina2) {
		this.disciplina = disciplina2;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_modulo_disciplina", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idModuloDisciplina) {
		this.id = idModuloDisciplina;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.EAGER)
	@JoinColumn(name = "id_modulo", unique = false, nullable = false, insertable = true, updatable = true)
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.EAGER)
	@JoinColumn(name = "id_disciplina", unique = false, nullable = false, insertable = true, updatable = true)
	public ComponenteCurricular getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(ComponenteCurricular disciplina) {
		this.disciplina = disciplina;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "modulo", "disciplina");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(modulo, disciplina);
	}

}
