package br.ufrn.sigaa.pesquisa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.sigaa.projetos.dominio.ModalidadeBolsaExterna;


/**
 * TipoBolsaExterna generated by hbm2java
 */
@Deprecated
@SuppressWarnings("serial")
@Entity
@Table(name = "tipo_bolsa_externa", schema = "pesquisa", uniqueConstraints = {})
public class TipoBolsaExterna implements PersistDB {

	// Fields
	/**
	 * Chave primária
	 */
	private int id;

	/**
	 * Modalidade da bolsa
	 */
	private ModalidadeBolsaExterna modalidadeBolsaExterna;

	/**
	 * Descrição do tipo da bolsa
	 */
	private String descricao;

	/**
	 * Valor da bolsa
	 */
	private Float valor;


	// Constructors

	/** default constructor */
	public TipoBolsaExterna() {
		modalidadeBolsaExterna = new ModalidadeBolsaExterna();
	}

	/** minimal constructor */
	public TipoBolsaExterna(int idTipoBolsaExterna) {
		this.id = idTipoBolsaExterna;
	}

	/** full constructor */
	public TipoBolsaExterna(int idTipoBolsaExterna,
			ModalidadeBolsaExterna modalidadeBolsaExterna, String descricao,
			Float valor) {

		this.id = idTipoBolsaExterna;
		this.modalidadeBolsaExterna = modalidadeBolsaExterna;
		this.descricao = descricao;
		this.valor = valor;
	}

	// Property accessors
	@Id
	@Column(name = "id_tipo_bolsa_externa", unique = true, nullable = false, insertable = true, updatable = true)
	@GeneratedValue(generator="seqGenerator")
	@GenericGenerator(name="seqGenerator", strategy="br.ufrn.arq.dao.SequenceStyleGenerator",
	           parameters={ @Parameter(name="sequence_name", value="hibernate_sequence") })
	public int getId() {
		return this.id;
	}

	public void setId(int idTipoBolsaExterna) {
		this.id = idTipoBolsaExterna;
	}

	//@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	//@JoinColumn(name = "id_modalidade_bolsa", unique = false, nullable = true, insertable = true, updatable = true)
	@Transient
	public ModalidadeBolsaExterna getModalidadeBolsaExterna() {
		return this.modalidadeBolsaExterna;
	}

	public void setModalidadeBolsaExterna(
			ModalidadeBolsaExterna modalidadeBolsaExterna) {
		this.modalidadeBolsaExterna = modalidadeBolsaExterna;
	}

	@Column(name = "descricao", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", unique = false, nullable = true, insertable = true, updatable = true, precision = 4, scale = 0)
	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id);
	}

}