/*
 * Universidade Federal do Rio Grande do Norte
 * Superintendência de Informática - UFRN
 * Diretoria de Sistemas
 *
 * Created on 13/09/2006
 *
 */
package br.ufrn.sigaa.projetos.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import br.ufrn.arq.negocio.validacao.ListaMensagens;
import br.ufrn.arq.negocio.validacao.Validatable;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.arq.util.ValidatorUtil;

/**
 * Representa o tipo de público alvo atingido pelo projeto
 * 
 * TipoPublicoAlvo generated by hbm2java
 * 
 */
@Entity
@Table(name = "tipo_publico_alvo", schema = "projetos", uniqueConstraints = {})
public class TipoPublicoAlvo implements Validatable {

	// Fields

	private int id;
	
	/** Descrição dos tipos de público alvo */ 
	private String descricao;

	/** Grupo do tipo de público alvo, utilizado para organizar a visualização */
	private GrupoPublicoAlvo grupo = new GrupoPublicoAlvo();
	
	/** Informa se o tipo de público alvo está ativo ou não. */
	private boolean ativo = true;

	/** Utilizado para adicionar e remover de listas. */
	private boolean selecionado;

	// Constructors

	/** default constructor */
	public TipoPublicoAlvo() {
	}

	/** default minimal constructor */
	public TipoPublicoAlvo(int id) {
		this.id = id;
	}

	/** minimal constructor */
	public TipoPublicoAlvo(int idTipoPublicoAlvo, String descricao) {
		this.id = idTipoPublicoAlvo;
		this.descricao = descricao;
	}

	// Property accessors
	@Id
	@GeneratedValue(generator="seqGenerator")
	@Column(name="id_tipo_publico_alvo")
	@GenericGenerator(name="seqGenerator", strategy="br.ufrn.arq.dao.SequenceStyleGenerator",
	           parameters={ @Parameter(name="sequence_name", value="hibernate_sequence") })	
	public int getId() {
		return this.id;
	}

	public void setId(int idTipoPublicoAlvo) {
		this.id = idTipoPublicoAlvo;
	}

	@ManyToOne
	@JoinColumn(name = "id_grupo")
	public GrupoPublicoAlvo getGrupo() {
		return grupo;
	}

	public void setGrupo(GrupoPublicoAlvo grupo) {
		this.grupo = grupo;
	}

	@Column(name = "descricao", unique = false, nullable = false, insertable = true, updatable = true, length = 120)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id", "descricao");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id, descricao);
	}

	public ListaMensagens validate() {
		ListaMensagens lista = new ListaMensagens();
		ValidatorUtil.validateRequired(descricao, "Descrição", lista);
		ValidatorUtil.validateRequired(grupo, "Grupo", lista);
		return lista;
	}

	@Transient
	public boolean isSelecionado() {
		return selecionado;
	}

	public void setSelecionado(boolean selecionado) {
		this.selecionado = selecionado;
	}

	public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

}
