/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '13/09/2006'
 *
 */
package br.ufrn.sigaa.pessoa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;

/**
 * Estrangeiro generated by hbm2java
 */
@Entity
@Table(name = "estrangeiro", uniqueConstraints = {})
public class Estrangeiro implements PersistDB {

	// Fields    

	private int id;

	private Pais paisByIdPais;

	private Pais paisByIdPaisDocumento;

	private Date dataChegada;

	private Date dataNaturalizacao;

	private String outroDocumento;

	// Constructors

	/** default constructor */
	public Estrangeiro() {
	}

	/** minimal constructor */
	public Estrangeiro(int idEstrangeiro) {
		this.id = idEstrangeiro;
	}

	/** full constructor */
	public Estrangeiro(int idEstrangeiro, Pais paisByIdPais,
			Pais paisByIdPaisDocumento, Date dataChegada,
			Date dataNaturalizacao, String outroDocumento) {
		this.id = idEstrangeiro;
		this.paisByIdPais = paisByIdPais;
		this.paisByIdPaisDocumento = paisByIdPaisDocumento;
		this.dataChegada = dataChegada;
		this.dataNaturalizacao = dataNaturalizacao;
		this.outroDocumento = outroDocumento;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_estrangeiro", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idEstrangeiro) {
		this.id = idEstrangeiro;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", unique = false, nullable = true, insertable = true, updatable = true)
	public Pais getPaisByIdPais() {
		return this.paisByIdPais;
	}

	public void setPaisByIdPais(Pais paisByIdPais) {
		this.paisByIdPais = paisByIdPais;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais_documento", unique = false, nullable = true, insertable = true, updatable = true)
	public Pais getPaisByIdPaisDocumento() {
		return this.paisByIdPaisDocumento;
	}

	public void setPaisByIdPaisDocumento(Pais paisByIdPaisDocumento) {
		this.paisByIdPaisDocumento = paisByIdPaisDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_chegada", unique = false, nullable = true, insertable = true, updatable = true, length = 4)
	public Date getDataChegada() {
		return this.dataChegada;
	}

	public void setDataChegada(Date dataChegada) {
		this.dataChegada = dataChegada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_naturalizacao", unique = false, nullable = true, insertable = true, updatable = true, length = 4)
	public Date getDataNaturalizacao() {
		return this.dataNaturalizacao;
	}

	public void setDataNaturalizacao(Date dataNaturalizacao) {
		this.dataNaturalizacao = dataNaturalizacao;
	}

	@Column(name = "outro_documento", unique = false, nullable = true, insertable = true, updatable = true, length = 20)
	public String getOutroDocumento() {
		return this.outroDocumento;
	}

	public void setOutroDocumento(String outroDocumento) {
		this.outroDocumento = outroDocumento;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id");
	}
	
	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id);
	}

}
