/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '13/09/2006'
 *
 */
package br.ufrn.sigaa.pessoa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import br.ufrn.arq.negocio.validacao.ListaMensagens;
import br.ufrn.arq.negocio.validacao.Validatable;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.arq.util.ValidatorUtil;

/**
 * TipoRaca generated by hbm2java
 */
@Entity
@Table(schema="comum", name = "tipo_raca", uniqueConstraints = {})
public class TipoRaca implements Validatable {

	// Fields

	/** Chave primária. */
	private int id;

	/** Descrição do Tipo de Raça. */
	private String descricao;

	// Constructors

	/** default constructor */
	public TipoRaca() {
	}

	/** default minimal constructor */
	public TipoRaca(int id) {
		this.id = id;
	}

	/** minimal constructor */
	public TipoRaca(int idTipoRaca, String descricao) {
		this.id = idTipoRaca;
		this.descricao = descricao;
	}

	/** full constructor */
	public TipoRaca(int idTipoRaca, String descricao, Set<Pessoa> pessoas) {
		this.id = idTipoRaca;
		this.descricao = descricao;
	}

	// Property accessors
	@Id 
	@GeneratedValue(generator="seqGenerator")
	@GenericGenerator(name="seqGenerator", strategy="br.ufrn.arq.dao.SequenceStyleGenerator",
	           parameters={ @Parameter(name="sequence_name", value="hibernate_sequence") })
	@Column(name = "id_tipo_raca", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idTipoRaca) {
		this.id = idTipoRaca;
	}

	@Column(name = "descricao", unique = false, nullable = false, insertable = true, updatable = true, length = 80)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}


	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id);
	}

	public ListaMensagens validate() {
		ListaMensagens lista = new ListaMensagens();
		ValidatorUtil.validateRequired(descricao, "Descrição", lista);
		return lista;
	}

	/** Retorna uma representação textual deste objeto no formato: descrição.
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return descricao;
	}
}