/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '13/09/2006'
 *
 */
package br.ufrn.sigaa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.ufrn.arq.dominio.PersistDB;

/**
 * ServidorFeriasId generated by hbm2java
 */
@Embeddable
public class ServidorFeriasId implements PersistDB {

	// Fields    

	private int id;

	private Date inicio;

	private Date fim;

	// Constructors

	/** default constructor */
	public ServidorFeriasId() {
	}

	/** default minimal constructor */
	public ServidorFeriasId(int id) {
		this.id = id;
	}
	
	/** full constructor */
	public ServidorFeriasId(int idServidor, Date inicio, Date fim) {
		this.id = idServidor;
		this.inicio = inicio;
		this.fim = fim;
	}

	// Property accessors

	@Column(name = "id_servidor", unique = false, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idServidor) {
		this.id = idServidor;
	}

	@Column(name = "inicio", unique = false, nullable = false, insertable = true, updatable = true, length = 4)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Column(name = "fim", unique = false, nullable = false, insertable = true, updatable = true, length = 4)
	public Date getFim() {
		return this.fim;
	}

	public void setFim(Date fim) {
		this.fim = fim;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServidorFeriasId))
			return false;
		ServidorFeriasId castOther = (ServidorFeriasId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getInicio() == castOther.getInicio()) || (this
						.getInicio() != null
						&& castOther.getInicio() != null && this.getInicio()
						.equals(castOther.getInicio())))
				&& ((this.getFim() == castOther.getFim()) || (this.getFim() != null
						&& castOther.getFim() != null && this.getFim().equals(
						castOther.getFim())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getInicio() == null ? 0 : this.getInicio().hashCode());
		result = 37 * result
				+ (getFim() == null ? 0 : this.getFim().hashCode());
		return result;
	}

}
