/*
 * Sistema Integrado de Gestão de Atividades Acadêmicas - SIGAA
 * Superintendência de Informática - UFRN
 *
 * Created on '01/12/2006'
 *
 */
package br.ufrn.sigaa.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.sigaa.pessoa.dominio.PessoaJuridica;

/**
 * TipoEsferaAdministrativa generated by hbm2java
 */
@Entity
@Table(name = "tipo_esfera_administrativa", uniqueConstraints = {})
public class TipoEsferaAdministrativa implements PersistDB {

	// Fields

	private int id;

	private String descricao;

	// Constructors

	/** default constructor */
	public TipoEsferaAdministrativa() {
	}

	/** minimal constructor */
	public TipoEsferaAdministrativa(int idTipoEsferaAdministrativa) {
		this.id = idTipoEsferaAdministrativa;
	}

	/** full constructor */
	public TipoEsferaAdministrativa(int idTipoEsferaAdministrativa,
			String descricao, Set<PessoaJuridica> pessoaJuridicas) {
		this.id = idTipoEsferaAdministrativa;
		this.descricao = descricao;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_tipo_esfera_administrativa", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(int idTipoEsferaAdministrativa) {
		this.id = idTipoEsferaAdministrativa;
	}

	@Column(name = "descricao", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}


	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testTransientEquals(this, obj, "id", "descricao");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id, descricao);
	}

}
