/*
 * Universidade Federal do Rio Grande do Norte
 * Superintendência de Informática - UFRN
 * Diretoria de Sistemas
 *
 * Created on 13/09/2006
 *
 */
package br.ufrn.sigaa.pesquisa.dominio;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.sigaa.projetos.dominio.EntidadeFinanciadora;

/**
 * ProgramaEntidadeFinanciadora generated by hbm2java
 */
@Deprecated
@SuppressWarnings("serial")
@Entity
@Table(name = "programa_entidade_financiadora", schema = "pesquisa",
		uniqueConstraints = { @UniqueConstraint(columnNames = {"id_programa_entidade_financiadora", "id_entidade_financiadora" }) })
public class ProgramaEntidadeFinanciadora implements PersistDB {

	// Fields    

	private int id;

	private String nome;
	
	private EntidadeFinanciadora entidadeFinanciadora = new EntidadeFinanciadora();

	private Set<FinanciamentoProjetoPesq> financiamentosProjetoPesq =
		new HashSet<FinanciamentoProjetoPesq>(0);

	// Constructors

	/** default constructor */
	public ProgramaEntidadeFinanciadora() {
	}

	/** default minimal constructor */
	public ProgramaEntidadeFinanciadora(int id) {
		this.id = id;
	}
	
	/** minimal constructor */
	public ProgramaEntidadeFinanciadora(int idProgramaEntidadeFinanciadora,
			EntidadeFinanciadora entidadeFinanciadora,
			ProgramaEntidadeFinanciadora programaEntidadeFinanciadora,
			String nome) {
		
		this.id = idProgramaEntidadeFinanciadora;
		this.entidadeFinanciadora = entidadeFinanciadora;
		this.nome = nome;
	}

	/** full constructor */
	public ProgramaEntidadeFinanciadora(int idProgramaEntidadeFinanciadora,
			EntidadeFinanciadora entidadeFinanciadora,
			ProgramaEntidadeFinanciadora programaEntidadeFinanciadora,
			String nome, 
			Set<ProgramaEntidadeFinanciadora> programaEntidadeFinanciadoras,
			Set<FinanciamentoProjetoPesq> financiamentosProjetoPesq) {
		
		this.id = idProgramaEntidadeFinanciadora;
		this.entidadeFinanciadora = entidadeFinanciadora;
		this.nome = nome;
		this.financiamentosProjetoPesq = financiamentosProjetoPesq;
	}

	// Property accessors
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_programa_entidade_financiadora", unique = true, nullable = false, insertable = true, updatable = true)
	public int getId() {
		return this.id;
	}

	public void setId(
			int idProgramaEntidadeFinanciadora) {
		this.id = idProgramaEntidadeFinanciadora;
	}

	@Column(name = "nome", unique = false, nullable = false, insertable = true, updatable = true, length = 80)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidade_financiadora", unique = false, nullable = false, insertable = true, updatable = true)
	public EntidadeFinanciadora getEntidadeFinanciadora() {
		return this.entidadeFinanciadora;
	}

	public void setEntidadeFinanciadora(
			EntidadeFinanciadora entidadeFinanciadora) {
		this.entidadeFinanciadora = entidadeFinanciadora;
	}
	
	
	@OneToMany(cascade = { }, fetch = FetchType.LAZY, mappedBy = "programaEntidadeFinanciadora")
	public Set<FinanciamentoProjetoPesq> getFinanciamentosProjetoPesq() {
		return this.financiamentosProjetoPesq;
	}

	public void setFinanciamentosProjetoPesq(
			Set<FinanciamentoProjetoPesq> financiamentoProjetoPesqs) {
		this.financiamentosProjetoPesq = financiamentoProjetoPesqs;
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testTransientEquals(this, obj, "id", "nome", "entidadeFinanciadora");
	}
	
	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id, nome, entidadeFinanciadora);
	}

}
