/*
 Name:    Highcharts
 Version: 1.2.0 (2010-02-23)
 Author:  Vevstein Web
 Support: www.highcharts.com/support
 License: www.highcharts.com/license
*/
(function(){function $b(a){if(!a||a.constructor!=Array)a=[a];return a}function bb(a){return a!==ia&&a!==null}function ua(){var a=arguments,b,c;for(b=0;b<a.length;b++){c=a[b];if(bb(c))return c}}function xb(a,b,c){var d,e="",f=c?"print":"",g=function(h){return R("style",{type:"text/css",media:h?"print":""},null,pa.getElementsByTagName("HEAD")[0])};ac||(ac=g());for(d in b)e+=Eb(d)+":"+b[d]+";";if(Ha){b=pa.styleSheets;c&&g(true);for(c=b.length-1;c>=0&&b[c].media!=f;)c--;f=b[c];f.addRule(a,e)}else ac.appendChild(pa.createTextNode(a+
" {"+e+"}\n"))}function I(a,b){a||(a={});for(var c in b)a[c]=b[c];return a}function Ec(a){return cb=V(cb,a)}function Aa(a){Fb||(Fb=R(Na));a&&Fb.appendChild(a);Fb.innerHTML=""}function db(a,b){var c=function(){};c.prototype=new a;I(c.prototype,b);return c}function Gb(a,b){if(typeof a=="string")return a;else if(a.linearGradient){var c=b.createLinearGradient.apply(b,a.linearGradient);o(a.stops,function(d){c.addColorStop(d[0],d[1])});return c}}function R(a,b,c,d,e){a=pa.createElement(a);b&&I(a,b);e&&
va(a,{padding:0,border:"none",margin:0});c&&va(a,c);d&&d.appendChild(a);return a}function va(a,b){if(Ha)if(b.opacity!==ia)b.filter="alpha(opacity="+b.opacity*100+")";I(a.style,b)}function Fc(a,b,c,d){a=a;var e=isNaN(b=Ia(b))?2:b;b=c===ia?".":c;d=d===ia?",":d;c=a<0?"-":"";var f=parseInt(a=Ia(+a||0).toFixed(e))+"",g=(g=f.length)>3?g%3:0;return c+(g?f.substr(0,g)+d:"")+f.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(e?b+Ia(a-f).toFixed(e).slice(2):"")}function pc(a,b,c){function d(u){return u.toString().replace(/^([0-9])$/,
"0$1")}if(!bb(b))return"Invalid date";b=new Date(b*Ja);var e=b.getUTCHours(),f=b.getUTCDay(),g=b.getUTCDate(),h=b.getUTCMonth(),j=b.getUTCFullYear(),m=cb.lang,r=m.weekdays;m=m.months;b={a:r[f].substr(0,3),A:r[f],d:d(g),e:g,b:m[h].substr(0,3),B:m[h],m:d(h+1),y:j.toString().substr(2,2),Y:j,H:d(e),I:d(e%12||12),l:e%12||12,M:d(b.getUTCMinutes()),p:e<12?"AM":"PM",P:e<12?"am":"pm",S:d(b.getUTCSeconds())};for(var v in b)a=a.replace("%"+v,b[v]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a}function Hb(a){for(var b=
{x:a.offsetLeft,y:a.offsetTop};a.offsetParent;){a=a.offsetParent;b.x+=a.offsetLeft;b.y+=a.offsetTop;if(a!=pa.body&&a!=pa.documentElement){b.x-=a.scrollLeft;b.y-=a.scrollTop}}return b}function Gc(a){function b(l,i){var x;i=ua(i,true);ja(s,"addSeries",{options:l},function(){x=d(l);x.isDirty=true;s.isDirty=true;i&&s.redraw()});return x}function c(){var l=s.isDirty;o(xa,function(i){if(i.isDirty){i.cleanData();i.getSegments();if(i.options.legendType=="point")l=true}});tb=null;if(Ib){o(Da,function(i){i.setScale()});
j();o(Da,function(i){i.isDirty&&i.redraw()})}o(xa,function(i){i.isDirty&&i.redraw()});if(l){if(Jb.renderHTML){Jb.renderHTML(true);Jb.drawGraphics(true)}s.isDirty=false}Kb.resetTracker();ja(s,"redraw")}function d(l){var i=l.type||z.defaultSeriesType,x=Hc[i],w=s.hasRendered;if(w)if(Oa&&i=="column")x=qc;else if(!Oa&&i=="bar")x=Lb;i=new x;i.init(s,l);if(!w&&i.inverted)Oa=true;xa.push(i);return i}function e(){var l=a.loading;if(!mb){mb=R(Na,{className:"highcharts-loading"},I(l.style,{left:fa+F,top:L+F,
width:qa+F,height:ha+F,zIndex:10,display:"none"}),la);R("span",{innerHTML:a.lang.loading},l.labelStyle,mb)}va(mb,{display:""});ub(mb,{opacity:l.style.opacity},{duration:l.showDuration})}function f(){ub(mb,{opacity:0},{duration:a.loading.hideDuration,complete:function(){va(mb,{display:"none"})}})}function g(l){var i,x,w;for(i=0;i<Da.length;i++)if(Da[i].options.id==l)return Da[i];for(i=0;i<xa.length;i++)if(xa[i].options.id==l)return xa[i];for(i=0;i<xa.length;i++){w=xa[i].data;for(x=0;x<w.length;x++)if(w[x].id==
l)return w[x]}return null}function h(){var l=a.xAxis||{},i=a.yAxis||{},x;l=$b(l);o(l,function(w,U){w.index=U;w.isX=true});i=$b(i);o(i,function(w,U){w.index=U});Da=l.concat(i);s.xAxis=[];s.yAxis=[];Da=jb(Da,function(w){x=new ra(s,w);s[x.isXAxis?"xAxis":"yAxis"].push(x);return x});j()}function j(){z.alignTicks!==false&&o(Da,function(l){l.adjustTickAmount()})}function m(){var l=[];o(xa,function(i){l=l.concat(Mb(i.data,function(x){return x.selected}))});return l}function r(){return Mb(xa,function(l){return l.selected})}
function v(l){s.toolbar.add("zoom","Reset zoom","Reset zoom level 1:1",function(){ja(s,"selection",{resetSelection:true},v);s.toolbar.remove("zoom")});!l||l.resetSelection?o(Da,function(i){i.setExtremes(null,null,false)}):o(l.xAxis.concat(l.yAxis),function(i){var x=i.axis;if(s.tracker[x.isXAxis?"zoomX":"zoomY"])x.setExtremes(i.min,i.max,false)});c()}function u(){var l=a.title,i=a.subtitle;if(!s.titleLayer){var x=new ma("title-layer",la,null,{zIndex:2});l&&l.text&&R("h2",{className:"highcharts-title",
innerHTML:l.text},l.style,x.div);i&&i.text&&R("h3",{className:"highcharts-subtitle",innerHTML:i.text},i.style,x.div);s.titleLayer=x}}function A(){var l=true;for(var i in s.resources)s.resources[i]||(l=false);l&&B()}function B(){h();o(xa,function(l){l.translate();l.setTooltipPoints();a.tooltip.enabled&&l.createArea()});s.render=na;setTimeout(function(){na();ja(s,"load")},0)}function S(){Pa=z.renderTo;bc="highcharts-"+cc++;if(typeof Pa=="string")Pa=pa.getElementById(Pa);Pa.innerHTML="";if(!Pa.offsetWidth){kb=
Pa.cloneNode(0);va(kb,{position:sa,top:"-9999px",display:""});pa.body.appendChild(kb)}var l=(kb||Pa).offsetHeight;eb=z.width||(kb||Pa).offsetWidth||600;Ba=z.height||(l>L+Sa?l:0)||400;la=R(Na,{className:"highcharts-container"+(z.className?" "+z.className:""),id:bc},I({position:Nb,overflow:Ta,width:eb+F,height:Ba+F,textAlign:"left"},z.style),kb||Pa)}function na(){var l,i=a.labels,x=a.credits;l=2*(z.borderWidth||0)+(z.shadow?8:0);rc.drawRect(l/2,l/2,eb-l,Ba-l,z.borderColor,z.borderWidth,z.borderRadius,
z.backgroundColor,z.shadow);rc.drawRect(fa,L,qa,ha,null,null,null,z.plotBackgroundColor,null,Ob);(new ma("plot-border",la,null,{zIndex:4})).drawRect(fa,L,qa,ha,z.plotBorderColor,z.plotBorderWidth,null,null,z.plotShadow);Ha&&xb(".highcharts-image-map",{display:"none"},"print");Ib&&o(Da,function(w){w.render()});u();i.items&&o(i.items,function(){var w=I({className:"highcharts-label"},this.attributes);dc.drawHtml(this.html,w,I(i.style,this.style))});o(xa,function(w){w.render()});Jb=s.legend=new fb(s);
if(!s.toolbar)s.toolbar=yb(s);if(x.enabled&&!s.credits);/*s.credits=R("a",{className:"highcharts-credits",href:x.href,innerHTML:x.text,target:x.target},I(x.style,{zIndex:8}),la);*/s.hasRendered=true;if(kb){Pa.appendChild(la);Aa(kb);Ua=Hb(la)}}function ra(l,i){function x(){i=V(ka?Pb:ec,Y?ya?Ic:sc:ya?Jc:Kc,i)}function w(){var k=[],p;Ea=Ka=null;Qb=[];o(xa,function(t){p=false;if(!(!t.visible&&z.ignoreHiddenSeries)){o(["xAxis","yAxis"],function(M){if((M=="xAxis"&&ka||M=="yAxis"&&!ka)&&(t.options[M]==i.index||
t.options[M]===ia&&i.index==0)){t[M]=Qa;Qb.push(t);p=true}});if(p){var y;if(!ka){y=t.options.stacking;Rb=y=="percent";if(y){var D=k[t.type]||[];k[t.type]=D}if(Rb){Ea=0;Ka=99}}if(t.isCartesian){Ib=true;o(t.data,function(M){var J=M.x,G=M.y;if(Ea===null)Ea=Ka=M[Sb];if(ka)if(J>Ka)Ka=J;else{if(J<Ea)Ea=J}else{if(y)D[J]=D[J]?D[J]+G:G;M=D?D[J]:G;if(!Rb)if(M>Ka)Ka=M;else if(M<Ea)Ea=M;if(y)gb[t.type][J]={total:M,cum:M}}});if(!ka&&/(area|column|bar)/.test(t.type))if(Ea>=0){Ea=0;tc=true}else if(Ka<0){Ka=0;uc=
true}}}}})}function U(k,p,t){var y=1,D=0;if(t){y*=-1;D=zb}if(nb){y*=-1;D-=y*zb}if(p){if(nb)k=zb-k;k=k/ob+ba}else k=y*(k-ba)*ob+D;return k}function ga(k,p,t){if(t){var y,D,M;y=U(k);k=D=y+Tb;y=M=Ba-y-Tb;if(Y){y=L;M=Ba-Sa}else{k=fa;D=eb-Va}vc.drawLine(k,y,D,M,p,t)}}function ta(k,p,t){k=fc(k,ba);p=Math.min(p,ca);var y=(p-k)*ob;ga(k+(p-k)/2,t,y)}function C(k,p,t,y,D,M,J){var G,Wa,Z,K=i.labels;if(p=="inside")D=-D;if(ya)D=-D;p=Wa=U(k+pb)+Tb;G=Z=Ba-U(k+pb)-Tb;if(Y){G=Ba-Sa-(ya?ha:0)+lb;Z=G+D}else{p=fa+(ya?
qa:0)+lb;Wa=p-D}y&&vb.drawLine(p,G,Wa,Z,t,y);if(M&&K.enabled)if((k=Ub.call({index:J,isFirst:k==aa[0],isLast:k==aa[aa.length-1],value:Fa&&Fa[k]?Fa[k]:k}))||k===0)vb.addText(k,p+K.x-(pb&&Y?pb*ob*(nb?-1:1):0),G+K.y-(pb&&!Y?pb*ob*(nb?1:-1):0),K.style,K.rotation,K.align)}function da(k,p){var t;ua(i.allowDecimals,true);Ab=p?1:wa.pow(10,Ra(wa.log(k)/wa.LN10));t=k/Ab;p||(p=[1,2,2.5,5,10]);for(var y=0;y<p.length;y++){k=p[y];if(t<=(p[y]+(p[y+1]||p[y]))/2)break}k*=Ab;return k}function Q(){aa=[];for(var k=1E3/
Ja,p=6E4/Ja,t=36E5/Ja,y=864E5/Ja,D=6048E5/Ja,M=2592E6/Ja,J=31556952E3/Ja,G=[["second",k,[1,2,5,10,15,30]],["minute",p,[1,2,5,10,15,30]],["hour",t,[1,2,3,4,6,8,12]],["day",y,[1,2]],["week",D,[1,2]],["month",M,[1,2,3,4,6]],["year",J,null]],Wa=G[6],Z=Wa[1],K=Wa[2],Xa=0;Xa<G.length;Xa++){Wa=G[Xa];Z=Wa[1];K=Wa[2];if(G[Xa+1]){var Lc=(Z*K[K.length-1]+G[Xa+1][1])/2;if(Ca<=Lc)break}}if(Z==J&&Ca<5*Z)K=[1,2,5];G=da(Ca/Z,K);var qb;K=new Date(ba*Ja);K.setUTCMilliseconds(0);if(Z>=k)K.setUTCSeconds(Z>=p?0:G*Ra(K.getUTCSeconds()/
G));if(Z>=p)K.setUTCMinutes(Z>=t?0:G*Ra(K.getUTCMinutes()/G));if(Z>=t)K.setUTCHours(Z>=y?0:G*Ra(K.getUTCHours()/G));if(Z>=y)K.setUTCDate(Z>=M?1:G*Ra(K.getUTCDate()/G));if(Z>=M){K.setUTCMonth(Z>=J?0:G*Ra(K.getUTCMonth()/G));qb=K.getUTCFullYear()}if(Z>=J){qb-=qb%G;K.setUTCFullYear(qb)}Z==D&&K.setUTCDate(K.getUTCDate()-K.getUTCDay()+i.startOfWeek);Xa=1;k=K.getTime()/Ja;qb=K.getUTCFullYear();for(p=K.getUTCMonth();k<ca&&Xa<qa;){aa.push(k);if(Z==J)k=Date.UTC(qb+Xa*G,0)/Ja;else if(Z==M)k=Date.UTC(qb,p+Xa*
G)/Ja;else k+=Z*G;Xa++}aa.push(k);i.labels.formatter||(Ub=function(){return pc(i.dateTimeLabelFormats[Wa[0]],this.value,1)})}function T(){var k=function(y){var D=(Ab<1?1/Ab:1)*10;return N(y*D)/D},p;p=Ra(ba/Ca)*Ca;var t=wa.ceil(ca/Ca)*Ca;aa=[];for(p=k(p);p<=t;){aa.push(p);p=k(p+Ca)}if(Fa){ba-=0.5;ca+=0.5}Ub||(Ub=function(){return this.value})}function W(){rb?Q():T();var k=aa[0],p=aa[aa.length-1];if(i.startOnTick)ba=k;else ba>k&&aa.shift();if(i.endOnTick)ca=p;else ca<p&&aa.pop()}function za(){if(!rb&&
!Fa){var k=wb,p=aa.length;wb=tb[Sb];if(p<wb){for(;aa.length<wb;)aa.push(aa[aa.length-1]+Ca);ob*=(p-1)/(wb-1)}if(bb(k)&&wb!=k)Qa.isDirty=true}}function q(){var k,p,t,y=ba,D=ca;k=i.maxZoom;w();ba=ua(wc,i.min,Ea);ca=ua(xc,i.max,Ka);if(ca-ba<k){k=(k-ca+ba)/2;ba-=k;ca+=k}if(!Fa&&!Rb){k=ca-ba||1;if(!bb(i.min)&&yc&&(Ea<0||!tc))ba-=k*yc;if(!bb(i.max)&&zc&&(Ka>0||!uc))ca+=k*zc}Ca=Fa||ba==ca?1:i.tickInterval=="auto"?(ca-ba)*i.tickPixelInterval/zb:i.tickInterval;rb||(Ca=da(Ca));gc=i.minorTickInterval=="auto"&&
Ca?Ca/5:i.minorTickInterval;W();ob=zb/(ca-ba||1);tb||(tb={x:0,y:0});if(!rb&&aa.length>tb[Sb])tb[Sb]=aa.length;if(!ka)for(p in gb)for(t in gb[p])gb[p][t].cum=gb[p][t].total;Qa.isDirty=ba!=y||ca!=D}function X(k,p,t){t=ua(t,true);ja(Qa,"setExtremes",{min:k,max:p},function(){if(Fa){if(k<0)k=0;if(p>Fa.length-1)p=Fa.length-1}wc=k;xc=p;t&&l.redraw()})}function E(){return{min:ba,max:ca,dataMin:Ea,dataMax:Ka}}function n(k){var p=k.width,t=p?hc:ic;t.push(k);p?ga(k.value,k.color,k.width):ta(k.from,k.to,k.color)}
function H(k){o([ic,hc],function(p){for(var t=0;t<p.length;t++)if(p[t].id==k){p.splice(t,1);break}});La()}function ea(){Kb.resetTracker();La();o(Qb,function(k){k.isDirty=true})}function La(){var k=i.title,p=i.alternateGridColor,t=i.minorTickWidth,y=i.lineWidth,D,M;vb.clear();vc.clear();if(!(!Qb.length||!bb(ba)||!bb(ca))){p&&o(aa,function(J,G){if(G%2==0&&J<ca)ta(J,aa[G+1]!==ia?aa[G+1]:ca,p)});o(ic,function(J){ta(J.from,J.to,J.color)});if(gc&&!Fa)for(D=ba;D<=ca;D+=gc){ga(D,i.minorGridLineColor,i.minorGridLineWidth);
t&&C(D,i.minorTickPosition,i.minorTickColor,t,i.minorTickLength)}o(aa,function(J,G){M=J+pb;ga(M,i.gridLineColor,i.gridLineWidth);C(J,i.tickPosition,i.tickColor,i.tickWidth,i.tickLength,!(J==ba&&!i.showFirstLabel||J==ca&&!i.showLastLabel),G)});o(hc,function(J){ga(J.value,J.color,J.width)});if(y){t=fa+(ya?qa:0)+lb;D=Ba-Sa-(ya?ha:0)+lb;vb.drawLine(Y?fa:t,Y?D:L,Y?eb-Va:t,Y?D:Ba-Sa,i.lineColor,y)}if(k&&k.enabled&&k.text){y=Y?fa:L;t=Y?qa:ha;y={low:y+(Y?0:t),middle:y+t/2,high:y+(Y?t:0)}[k.align];t=(Y?L+
ha:fa)+(Y?1:-1)*(ya?-1:1)*k.margin-(Ha?parseInt(k.style.fontSize||k.style.font.replace(/^[a-z ]+/,""))/3:0);vb.addText(k.text,Y?y:t+(ya?qa:0)+lb,Y?t-(ya?ha:0)+lb:y,k.style,k.rotation||0,{low:"left",middle:"center",high:"right"}[k.align])}vb.strokeText();Qa.isDirty=false}}var ka=i.isX,ya=i.opposite,Y=Oa?!ka:ka,gb={bar:{},column:{},area:{},areaspline:{}};x();var Qa=this,rb=i.type=="datetime",lb=i.offset||0,Sb=ka?"x":"y",zb=Y?qa:ha,ob,Tb=Y?fa:Sa,vb=new ma("axis-layer",la,null,{zIndex:7}),vc=new ma("grid-layer",
la,null,{zIndex:1}),Ea,Ka,Qb,wc,xc,ca=null,ba=null,yc=i.minPadding,zc=i.maxPadding,tc,uc,Rb,Ac=i.events,jc,ic=i.plotBands||[],hc=i.plotLines||[],Ca,gc,Ab,aa,wb,Ub=i.labels.formatter,Fa=i.categories||ka&&l.columnCount,nb=i.reversed,pb=Fa&&i.tickmarkPlacement=="between"?0.5:0;if(Oa&&ka&&nb===ia)nb=true;ya||(lb*=-1);if(Y)lb*=-1;I(Qa,{addPlotBand:n,addPlotLine:n,adjustTickAmount:za,categories:Fa,getExtremes:E,isXAxis:ka,options:i,render:La,setExtremes:X,setScale:q,translate:U,redraw:ea,removePlotBand:H,
removePlotLine:H,reversed:nb,stacks:gb});for(jc in Ac)Ma(Qa,jc,Ac[jc]);q()}function yb(){function l(U,ga,ta,C){if(!w[U]){ga=R(Na,{innerHTML:ga,title:ta,onclick:C},I(a.toolbar.itemStyle,{zIndex:1003}),x.div);w[U]=ga}}function i(U){Aa(w[U]);w[U]=null}var x,w={};x=new ma("toolbar",la,null,{zIndex:1004,width:"auto",height:"auto"});return{add:l,remove:i}}function hb(l,i){function x(n){n=n||Ya.event;if(!n.target)n.target=n.srcElement;if(!n.pageX)n.pageX=n.clientX+(pa.documentElement.scrollLeft||pa.body.scrollLeft);
if(!n.pageY)n.pageY=n.clientY+(pa.documentElement.scrollTop||pa.body.scrollTop);return n}function w(n){var H={xAxis:[],yAxis:[]};o(Da,function(ea){var La=ea.translate,ka=ea.isXAxis,ya=Oa?!ka:ka;H[ka?"xAxis":"yAxis"].push({axis:ea,value:La(ya?n.pageX-Ua.x-fa:ha-n.pageY+Ua.y+L,true)})});return H}function U(){Za.onmousedown=function(n){n=x(n);n.preventDefault&&n.preventDefault();l.mouseIsDown=Bb=true;T=n.pageX;W=n.pageY;if(Ib&&(X||E)){q||(q=R(Na,null,{position:sa,border:"none",background:"#4572A7",opacity:0.25,
width:X?0:qa+F,height:E?0:ha+F}));dc.div.appendChild(q)}};Za.onmousemove=function(n){n=x(n);n.returnValue=false;if(Bb){za=Math.sqrt(Math.pow(T-n.pageX,2)+Math.pow(W-n.pageY,2))>10;if(X){var H=n.pageX-T;va(q,{width:Ia(H)+F,left:(H>0?0:H)+T-Ua.x-fa+F})}if(E){n=n.pageY-W;va(q,{height:Ia(n)+F,top:(n>0?0:n)+ +W-Ua.y-L+F})}}else ga(n);return false};Za.onmouseup=function(){var n;if(q){var H={xAxis:[],yAxis:[]},ea=q.offsetLeft,La=q.offsetTop,ka=q.offsetWidth,ya=q.offsetHeight;if(za){o(Da,function(Y){var gb=
Y.translate,Qa=Y.isXAxis,rb=Oa?!Qa:Qa;H[Qa?"xAxis":"yAxis"].push({axis:Y,min:gb(rb?ea:ha-La-ya,true),max:gb(rb?ea+ka:ha-La,true)})});ja(l,"selection",H,v);n=true}Aa(q);q=null}l.mouseIsDown=Bb=za=false};Za.onmouseout=function(n){n=n||Ya.event;if((n=n.relatedTarget||n.toElement)&&n!=Vb&&n.tagName!="AREA"){C();l.mouseIsDown=Bb=za=false}};Za.onclick=function(n){n=x(n);n.cancelBubble=true;if(!za)if(Q&&n.target.tagName=="AREA"){var H=Q.plotX,ea=Q.plotY;I(Q,{pageX:Ua.x+fa+(Oa?qa-ea:H),pageY:Ua.y+L+(Oa?ha-
H:ea)});ja(l.hoverSeries,"click",I(n,{point:Q}));Q.firePointEvent("click",n)}else{I(n,w(n));ja(l,"click",n)}za=false}}function ga(n){var H=l.hoverPoint,ea=l.hoverSeries;if(ea){H||(H=ea.tooltipPoints[Oa?n.pageY-Ua.y-L:n.pageX-Ua.x-fa]);if(H&&H!=Q){Q&&Q.firePointEvent("mouseOut");H.firePointEvent("mouseOver");Wb.refresh(H);Q=H}}}function ta(){var n="highchartsMap"+Mc++;l.imagemap=Za=R("map",{name:n,id:n,className:"highcharts-image-map"},null,la);Vb=R("img",{useMap:"#"+n},{width:qa+F,height:ha+F,left:fa+
F,top:L+F,opacity:0,border:"none",position:sa,clip:"rect(1px,"+qa+"px,"+ha+"px,1px)",zIndex:9},Za);if(!Ha)Vb.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="}function C(){Wb.hide();if(l.hoverSeries){l.hoverSeries.setState();Q=l.hoverSeries=null}}function da(n){var H=0,ea,La=Za.childNodes;for(ea=0;ea<La.length;ea++)if(La[ea].isLegendArea){H=ea+1;break}Za.insertBefore(n,La[H])}if(i.enabled){var Q,T,W,za,q,X=/x/.test(l.options.chart.zoomType),E=/y/.test(l.options.chart.zoomType);
ta();l.tooltip=Wb=$a(i);U();setInterval(function(){kc&&kc()},32);I(this,{insertAtFront:da,zoomX:X,zoomY:E,resetTracker:C})}}function $a(l){function i(da,Q){var T=da.tooltipPos;Q=da.series;var W=l.borderColor||da.color||Q.color||"#606060",za=s.inverted,q,X,E,n=ga.offsetHeight;E=da.tooltipText;U=Q;q=T?T[0]:za?qa-da.plotY:da.plotX;T=T?T[1]:za?ha-da.plotX:da.plotY;if(q>=0&&q<=qa&&T>=0&&T<=ha)X=true;if(E===false||!X)w();else{ga.innerHTML=E;X=ga.offsetWidth-ta;E=ga.offsetHeight-ta;if(X>(C.w||0)+20||X<(C.w||
0)-20||E>C.h||C.c!=W||n!=ga.offsetHeight){C.clear();C.drawRect(ta/2,ta/2,X+20,E,W,ta,l.borderRadius,l.backgroundColor,l.shadow);I(C,{w:X,h:E,c:W})}W=q-C.w+fa-35;q=T-C.h+10+L;if(W<5){W=5;q-=20}if(q<5)q=5;else if(q+C.h>Ba)q=Ba-C.h-5;x(N(W),N(q));Q.drawPointState(da,"hover");ab.style.visibility=lc}}function x(da,Q){var T=ab.style.visibility==Ta,W=T?da:(ab.offsetLeft+da)/2;T=T?Q:(ab.offsetTop+Q)/2;va(ab,{left:W+F,top:T+F});kc=Ia(da-W)>1||Ia(Q-T)>1?function(){x(da,Q)}:null}function w(){if(ab)ab.style.visibility=
Ta;U&&U.drawPointState()}var U,ga,ta=l.borderWidth,C;ab=R(Na,null,{position:sa,visibility:Ta,overflow:Ta,padding:"0 50px 5px 0",zIndex:8},la);C=new ma("tooltip-box",ab,null,{width:eb+F,height:Ba+F});ga=R(Na,{className:"highcharts-tooltip"},I(l.style,{maxWidth:eb-40+F,overflow:Ta,textOverflow:"ellipsis",position:Nb,zIndex:2}),ab);return{refresh:i,hide:w}}var fb=function(l){function i(za){if(za){o(Q,function(q){Aa(q.legendItem)});Q=[]}o(l.series,function(q){if(q.options.showInLegend){var X=q.options.legendType==
"point"?q.data:[q];o(X,function(E){E.simpleSymbol=/(bar|pie|area|column)/.test(q.type);E.legendItem=U=R("li",{innerHTML:w.labelFormatter.call(E),className:E.visible?"":Cb},null,C.firstChild);if(E.options&&E.options.showCheckbox)E.checkbox=R("input",{type:"checkbox",checked:E.selected,defaultChecked:E.selected},w.itemCheckboxStyle,U);Ma(U,"mouseover",function(){E.setState("hover")});Ma(U,"mouseout",function(){E.setState()});Ma(U,"click",function(n){n=n.target;var H="legendItemClick",ea=function(){E.setVisible()};
if(n.tagName=="INPUT")ja(E,"checkboxClick",{checked:n.checked},function(){E.select()});else E.firePointEvent?E.firePointEvent(H,null,ea):ja(E,H,null,ea)});Q.push(E)})}})}function x(za){if(za){T.clear();Aa(W);W=null}if(xa.length){if(w.borderWidth||w.backgroundColor)T.drawRect(C.offsetLeft,C.offsetTop,C.offsetWidth,C.offsetHeight,w.borderColor,w.borderWidth,w.borderRadius,w.backgroundColor,w.shadow);o(Q,function(q){if(q.legendItem){var X=q.legendItem,E=C.offsetLeft+X.offsetLeft;X=C.offsetTop+X.offsetTop+
X.offsetHeight/2;var n=q.legendItem.className==Cb,H=n?w.itemHiddenStyle.color:q.color;!q.simpleSymbol&&q.options&&q.options.lineWidth&&T.drawLine(E,X,E+ta,X,H,q.options.lineWidth);if(q.simpleSymbol)T.drawRect(E,X-6,16,12,null,0,2,H);else if(q.options&&q.options.marker&&q.options.marker.enabled)q.drawMarker(T,E+ta/2,X,V(q.options.marker,n?{fillColor:H,lineColor:H}:null))}});if(Za){W=R("area",{shape:"rect",isLegendArea:true,coords:[C.offsetLeft-fa,C.offsetTop-L,C.offsetLeft+C.offsetWidth-fa,C.offsetTop+
C.offsetHeight-L].join(",")});Kb.insertAtFront(W);W.onmouseover=function(q){q=q||Ya.event;q=q.relatedTarget||q.fromElement;if(q!=C&&!Bb){Wb.hide();va(C,{zIndex:10})}};C.onmouseout=W.onmouseout=function(q){q=q||Ya.event;if((q=q.relatedTarget||q.toElement)&&(q==Vb||q.tagName=="AREA"&&q!=W))va(C,{zIndex:7})}}}}var w=l.options.legend;if(w.enabled){var U,ga=w.layout,ta=w.symbolWidth,C,da="#"+la.id+" .highcharts-legend li",Q=[],T=new ma("legend",la,null,{zIndex:7}),W;this.dom=C=R(Na,{className:"highcharts-legend highcharts-legend-"+
ga,innerHTML:'<ul style="margin:0;padding:0"></ul>'},I({position:sa,zIndex:7},w.style),la);xb(da,I(w.itemStyle,{paddingLeft:ta+w.symbolPadding+F,"float":ga=="horizontal"?"left":"none"}));xb(da+":hover",w.itemHoverStyle);xb(da+"."+Cb,w.itemHiddenStyle);xb(".highcharts-legend-horizontal li",{"float":"left"});i();x();return{renderHTML:i,drawGraphics:x}}};Pb=V(Pb,cb.xAxis);ec=V(ec,cb.yAxis);cb.xAxis=cb.yAxis=null;a=V(cb,a);var z=a.chart,O=z.margin;O=typeof O=="number"?[O,O,O,O]:O;var L=O[0],Va=O[1],Sa=
O[2],fa=O[3],Pa,kb,la,bc,eb,Ba;S();var s=this;O=z.events;var mc,Za,Wb,Bb,rc=new ma("chart-background",la),mb,dc,ha,qa,Kb,Vb,Jb,Ua=Hb(la),Ib,Da=[],tb,xa=[],Ob,Oa,kc,ab,Hc={line:Nc,spline:Bc,area:Oc,areaspline:Pc,column:Lb,bar:qc,pie:Qc,scatter:Rc};Xb=sb=0;Ma(Ya,"resize",function(){var l=pa.getElementById(bc);if(l)Ua=Hb(l)});if(O)for(mc in O)Ma(s,mc,O[mc]);s.addLoading=function(l){s.resources[l]=false};s.clearLoading=function(l){s.resources[l]=true;A()};s.options=a;s.series=xa;s.resources={};s.inverted=
Oa=a.chart.inverted;s.chartWidth=eb;s.chartHeight=Ba;s.plotWidth=qa=eb-fa-Va;s.plotHeight=ha=Ba-L-Sa;s.plotLeft=fa;s.plotTop=L;s.redraw=c;s.addSeries=b;s.getSelectedPoints=m;s.getSelectedSeries=r;s.showLoading=e;s.hideLoading=f;s.get=g;s.updatePosition=Hb;s.plotLayer=dc=new ma("plot",la,null,{position:sa,width:qa+F,height:ha+F,left:fa+F,top:L+F,overflow:Ta,zIndex:3});s.tracker=Kb=new hb(s,a.tooltip);if(z.plotBackgroundImage){s.addLoading("plotBack");Ob=R("img");Ob.onload=function(){s.clearLoading("plotBack")};
Ob.src=z.plotBackgroundImage}o(a.series,function(l){d(l)});A()}function Cc(a){for(var b=[],c=[],d=0;d<a.length;d++){b[d]=a[d].plotX;c[d]=a[d].plotY}this.xdata=b;this.ydata=c;a=[];this.y2=[];var e=c.length;this.n=e;this.y2[0]=0;this.y2[e-1]=0;a[0]=0;for(d=1;d<e-1;d++){var f=b[d+1]-b[d-1];f=(b[d]-b[d-1])/f;var g=f*this.y2[d-1]+2;this.y2[d]=(f-1)/g;a[d]=(c[d+1]-c[d])/(b[d+1]-b[d])-(c[d]-c[d-1])/(b[d]-b[d-1]);a[d]=(6*a[d]/(b[d+1]-b[d-1])-f*a[d-1])/g}for(b=e-2;b>=0;b--)this.y2[b]=this.y2[b]*this.y2[b+
1]+a[b]}var ia,pa=document,Ya=window,wa=Math,N=wa.round,Ra=wa.floor,fc=wa.max,Ia=wa.abs,Yb=wa.cos,Zb=wa.sin,P=navigator.userAgent,Ha=/msie/i.test(P)&&!Ya.opera,Sc=/AppleWebKit/.test(P),ac,Mc=0,sb,Xb,Dc={},cc=0,Ja=1,Fb,Na="div",sa="absolute",Nb="relative",Ta="hidden",Cb="highcharts-"+Ta,lc="visible",F="px",oa=(P=Ya.HighchartsAdapter)||{},o=oa.each,Mb=oa.grep,jb=oa.map,V=oa.merge,Eb=oa.hyphenate,Ma=oa.addEvent,ja=oa.fireEvent,ub=oa.animate,nc=oa.getAjax;if(!P&&Ya.jQuery){var ib=jQuery;o=function(a,
b){for(var c=0,d=a.length;c<d;c++)if(b.call(a[c],a[c],c,a)===false)return c};Mb=ib.grep;jb=function(a,b){for(var c=[],d=0,e=a.length;d<e;d++)c[d]=b.call(a[d],a[d],d,a);return c};V=function(){var a=arguments;return ib.extend(true,null,a[0],a[1],a[2],a[3])};Eb=function(a){return a.replace(/([A-Z])/g,function(b,c){return"-"+c.toLowerCase()})};Ma=function(a,b,c){ib(a).bind(b,c)};ja=function(a,b,c,d){var e=ib.Event(b),f="detached"+b;I(e,c);if(a[b]){a[f]=a[b];a[b]=null}ib(a).trigger(e);if(a[f]){a[b]=a[f];
a[f]=null}d&&!e.isDefaultPrevented()&&d(e)};ub=function(a,b,c){ib(a).animate(b,c)};nc=function(a,b){ib.get(a,null,b)};ib.extend(ib.easing,{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}})}else if(!P&&Ya.MooTools){o=$each;jb=function(a,b){return a.map(b)};Mb=function(a,b){return a.filter(b)};V=$merge;Eb=function(a){return a.hyphenate()};Ma=function(a,b,c){if(!a.addEvent)if(a.nodeName)a=$(a);else I(a,new Events);a.addEvent(b,c)};ja=function(a,b,c,d){b=new Event({type:b,target:a});b=I(b,c);
b.preventDefault=function(){d=null};a.fireEvent&&a.fireEvent(b.type,b);d&&d(b)};ub=function(a,b,c){a=new Fx.Morph($(a),I(c,{transition:Fx.Transitions.Quad.easeInOut}));a.start(b)};nc=function(a,b){(new Request({url:a,method:"get",onSuccess:b})).send()}}P='normal 12px "Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif';oa={enabled:true,align:"center",x:0,y:15,style:{color:"#666",font:P.replace("12px","11px")}};var cb={colors:["#4572A7","#AA4643","#89A54E","#80699B","#3D96AE",
"#DB843D","#92A8CD","#A47D7C","#B5CA92"],symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:["January","February","March","April","May","June","July","August","September","October","November","December"],weekdays:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]},chart:{margin:[50,50,60,80],borderColor:"#4572A7",borderRadius:5,defaultSeriesType:"line",ignoreHiddenSeries:true,plotBorderColor:"#C0C0C0"},title:{text:"Chart title",
style:{textAlign:"center",color:"#3E576F",font:P.replace("12px","16px"),margin:"10px 0 0 0"}},subtitle:{text:"",style:{textAlign:"center",color:"#6D869F",font:P,margin:0}},plotOptions:{line:{allowPointSelect:false,showCheckbox:false,animation:true,events:{},lineWidth:2,shadow:true,marker:{enabled:true,symbol:"auto",lineWidth:0,radius:4,lineColor:"#FFFFFF",fillColor:"auto",states:{hover:{},select:{fillColor:"#FFFFFF",lineColor:"auto",lineWidth:2}}},point:{events:{}},dataLabels:V(oa,{enabled:false,
y:-6,formatter:function(){return this.y}}),showInLegend:true,states:{hover:{lineWidth:3,marker:{}},select:{marker:{}}}}},labels:{style:{position:sa,color:"#3E576F",font:P}},legend:{enabled:true,layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:5,shadow:true,style:{bottom:"10px",left:"80px",padding:"5px"},itemStyle:{listStyle:"none",margin:0,padding:"0 2em 0 0",font:P,cursor:"pointer",color:"#3E576F",position:Nb},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},
itemCheckboxStyle:{position:sa,right:0},symbolWidth:16,symbolPadding:5},loading:{hideDuration:100,labelStyle:{font:P.replace("normal","bold"),position:Nb,top:"1em"},showDuration:100,style:{position:sa,backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:true,formatter:function(){return"<b>"+(this.point.name||this.series.name)+"</b><br/>X value: "+this.x+"<br/>Y value: "+this.y},backgroundColor:"rgba(255, 255, 255, .85)",borderWidth:2,borderRadius:5,shadow:true,snap:10,style:{color:"#333333",
font:P,fontSize:"9pt",padding:"5px",whiteSpace:"nowrap"}},toolbar:{itemStyle:{color:"#4572A7",cursor:"pointer",margin:"20px",font:P}},credits:{enabled:true,text:"Highcharts.com",href:"http://www.highcharts.com",style:{position:sa,right:"10px",bottom:"5px",color:"#999",textDecoration:"none",font:P.replace("12px","10px")},target:"_self"}},Pb={dateTimeLabelFormats:{second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:false,gridLineColor:"#C0C0C0",
labels:oa,lineColor:"#C0D0E0",lineWidth:1,max:null,min:null,maxZoom:null,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",minorTickWidth:1,showFirstLabel:true,showLastLabel:false,startOfWeek:1,startOnTick:false,tickColor:"#C0D0E0",tickInterval:"auto",tickLength:5,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{enabled:false,text:"X-values",align:"middle",margin:35,style:{color:"#6D869F",
font:P.replace("normal","bold")}},type:"linear"},ec=V(Pb,{endOnTick:true,gridLineWidth:1,tickPixelInterval:72,showLastLabel:true,labels:{align:"right",x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:true,tickWidth:0,title:{enabled:true,margin:40,rotation:270,text:"Y-values"}}),Kc={labels:{align:"right",x:-8,y:3},title:{rotation:270}},Jc={labels:{align:"left",x:8,y:3},title:{rotation:90}},sc={labels:{align:"center",x:0,y:14},title:{rotation:0}},Ic=V(sc,{labels:{y:-5}});P=cb.plotOptions;
oa=P.line;P.spline=V(oa);P.scatter=V(oa,{lineWidth:0,states:{hover:{lineWidth:0}}});P.area=V(oa,{fillColor:"auto"});P.areaspline=V(P.area);P.column=V(oa,{borderColor:"#FFFFFF",borderWidth:1,borderRadius:0,groupPadding:0.2,pointPadding:0.1,states:{hover:{brightness:0.1,shadow:false},select:{color:"#C0C0C0",borderColor:"#000000",shadow:false}}});P.bar=V(P.column,{dataLabels:{align:"left",x:5,y:0}});P.pie=V(oa,{borderColor:"#FFFFFF",borderWidth:1,center:["50%","50%"],legendType:"point",size:"90%",slicedOffset:10,
states:{hover:{brightness:0.1,shadow:false}}});var oc=function(a){function b(h){if(g=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(h))f=[parseInt(g[1]),parseInt(g[2]),parseInt(g[3]),parseFloat(g[4])];else if(g=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(h))f=[parseInt(g[1],16),parseInt(g[2],16),parseInt(g[3],16),1]}function c(){return f&&!isNaN(f[0])?"rgba("+f.join(",")+")":a}function d(h){if(typeof h=="number"&&h!=0)for(var j=0;j<
3;j++){f[j]+=parseInt(h*255);if(f[j]<0)f[j]=0;if(f[j]>255)f[j]=255}return this}function e(h){f[3]=h;return this}var f=[],g;b(a);return{get:c,brighten:d,setOpacity:e}},ma=function(a,b,c,d){var e=this,f=b.style;c=I({className:"highcharts-"+a},c);d=I({width:f.width,height:f.height,position:sa,top:0,left:0,margin:0,padding:0,border:"none"},d);a=R(Na,c,d,b);I(e,{div:a,width:parseInt(d.width),height:parseInt(d.height)});e.svg=Ha?"":'<?xml version="1.0" encoding="utf-8"?><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="'+
e.width+'px" height="'+e.height+'">';e.basicSvg=e.svg};ma.prototype={getCtx:function(){if(!this.ctx){var a=R("canvas",{id:"highcharts-canvas-"+cc++,width:this.width,height:this.height},{position:sa},this.div);if(Ha){G_vmlCanvasManager.initElement(a);a=pa.getElementById(a.id)}this.ctx=a.getContext("2d")}return this.ctx},getSvg:function(){if(!this.svgObject){var a=this,b=a.div,c=a.width;a=a.height;if(Ha){if(!pa.namespaces.g_vml_){pa.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");pa.createStyleSheet().cssText=
"g_vml_\\:*{behavior:url(#default#VML)}"}this.svgObject=R(Na,null,{width:c+F,height:a+F,position:sa},b)}else this.svgObject=R("object",{width:c,height:a,type:"image/svg+xml"},{position:sa,left:0,top:0},b)}return this.svgObject},drawLine:function(a,b,c,d,e,f){var g=this.getCtx();if(a==c)a=c=N(a)+f%2/2;if(b==d)b=d=N(b)+f%2/2;g.lineWidth=f;g.lineCap="round";g.beginPath();g.moveTo(a,b);g.strokeStyle=e;g.lineTo(c,d);g.closePath();g.stroke()},drawPolyLine:function(a,b,c,d,e){var f=this.getCtx(),g=[];if(d&&
c){o(a,function(h){g.push(h===ia?h:h+1)});for(d=1;d<=3;d++)this.drawPolyLine(g,"rgba(0, 0, 0, "+0.05*d+")",6-2*d)}f.beginPath();for(d=0;d<a.length;d+=2)f[d==0?"moveTo":"lineTo"](a[d],a[d+1]);I(f,{lineWidth:c,lineJoin:"round"});if(b&&c){f.strokeStyle=Gb(b,f);f.stroke()}if(e){f.fillStyle=Gb(e,f);f.fill()}},drawRect:function(a,b,c,d,e,f,g,h,j,m){var r=function(){if(c>0&&d>0){v.beginPath();if(g){v.moveTo(a,b+g);v.lineTo(a,b+d-g);v.quadraticCurveTo(a,b+d,a+g,b+d);v.lineTo(a+c-g,b+d);v.quadraticCurveTo(a+
c,b+d,a+c,b+d-g);v.lineTo(a+c,b+g);v.quadraticCurveTo(a+c,b,a+c-g,b);v.lineTo(a+g,b);v.quadraticCurveTo(a,b,a,b+g)}else v.rect(a,b,c,d);v.closePath()}},v=this.getCtx(),u=(f||0)%2/2;a=N(a)+u;b=N(b)+u;c=N(c-2*u);d=N(d-2*u);if(j)for(j=1;j<=3;j++)this.drawRect(a+1,b+1,c,d,"rgba(0, 0, 0, "+0.05*j+")",6-2*j,g);m&&v.drawImage(m,a,b,c,d);r();if(h){v.fillStyle=Gb(h,v);v.fill();Ya.G_vmlCanvasManager&&r()}if(f){v.strokeStyle=Gb(e,v);v.lineWidth=f;v.stroke()}},drawSymbol:function(a,b,c,d,e,f,g){var h=this.getCtx(),
j=/^url\((.*?)\)$/;h.beginPath();if(a=="square"){a=0.707*d;h.moveTo(b-a,c-a);h.lineTo(b+a,c-a);h.lineTo(b+a,c+a);h.lineTo(b-a,c+a);h.lineTo(b-a,c-a)}else if(a=="triangle"){c++;h.moveTo(b,c-1.33*d);h.lineTo(b+d,c+0.67*d);h.lineTo(b-d,c+0.67*d);h.lineTo(b,c-1.33*d)}else if(a=="triangle-down"){c--;h.moveTo(b,c+1.33*d);h.lineTo(b-d,c-0.67*d);h.lineTo(b+d,c-0.67*d);h.lineTo(b,c+1.33*d)}else if(a=="diamond"){h.moveTo(b,c-d);h.lineTo(b+d,c);h.lineTo(b,c+d);h.lineTo(b-d,c);h.lineTo(b,c-d)}else j.test(a)?
R("img",{onload:function(){var m=this,r=Dc[m.src]||[m.width,m.height];va(m,{left:N(b-r[0]/2)+F,top:N(c-r[1]/2)+F,visibility:lc});Dc[m.src]=r},src:a.match(j)[1]},{position:sa,visibility:Ha?lc:Ta},this.div):h.arc(b,c,d,0,2*wa.PI,true);if(g){h.fillStyle=g;h.fill()}if(f&&e){h.strokeStyle=f||"rgb(100, 100, 255)";h.lineWidth=e||2;h.stroke()}},drawHtml:function(a,b,c){R(Na,I(b,{innerHTML:a}),I(c,{position:sa}),this.div)},drawText:function(){this.addText.apply(this,arguments);this.strokeText()},addText:function(a,
b,c,d,e,f){if(a||a===0){var g=this,h,j=g.div,m,r="";d=d||{};var v=d.color||"#000000";f=f||"left";var u=parseInt(d.fontSize||d.font.replace(/^[a-z ]+/,""));for(var A in d)r+=Eb(A)+":"+d[A]+";";o(["MozTransform","WebkitTransform","transform"],function(ra){if(ra in j.style)m=ra});if(!e||m){a=R("span",{innerHTML:a},I(d,{position:sa,left:b+F,whiteSpace:"nowrap",bottom:N(g.height-c-u*0.25)+F,color:v}),j);r=a.offsetWidth;if(f=="right")va(a,{left:b-r+F});else f=="center"&&va(a,{left:N(b-r/2)+F});if(e){f=
{left:0,center:50,right:100}[f];a.style[m]="rotate("+e+"deg)";a.style[m+"Origin"]=f+"% 100%"}}else if(Ha){h=true;d=(e||0)*wa.PI*2/360;e=Yb(d);d=Zb(d);A=g.width;u=u/3||3;var B=f=="left",S=f=="right",na=B?b:b-A*e;b=S?b:b+A*e;B=B?c:c-A*d;c=S?c:c+A*d;na+=u*d;b+=u*d;B-=u*e;c-=u*e;if(Ia(na-b)<0.1)na+=0.1;if(Ia(B-c)<0.1)B+=0.1;g.svg+='<g_vml_:line from="'+na+", "+B+'" to="'+b+", "+c+'" stroked="false"><g_vml_:fill on="true" color="'+v+'"/><g_vml_:path textpathok="true"/><g_vml_:textpath on="true" string="'+
a+'" style="v-text-align:'+f+";"+r+'"/></g_vml_:line>'}else{h=true;g.svg+='<g><text transform="translate('+b+","+c+") rotate("+(e||0)+')" style="fill:'+v+";text-anchor:"+{left:"start",center:"middle",right:"end"}[f]+";"+r.replace(/"/g,"'")+'">'+a+"</text></g>"}g.hasObject=h}},strokeText:function(){if(this.hasObject){var a=this.getSvg(),b=this.svg;if(Ha)a.innerHTML=b;else{a.data="data:image/svg+xml,"+b+"</svg>";Sc&&this.div.appendChild(a)}}},clear:function(){var a=this,b=this.div;b=b.childNodes;a.ctx&&
a.ctx.clearRect(0,0,a.width,a.height);if(a.svgObject){Aa(a.svgObject);a.svgObject=null;a.svg=a.basicSvg}for(var c=b.length-1;c>=0;c--){a=b[c];a.tagName=="SPAN"&&Aa(a)}},hide:function(){va(this.div,{display:"none"})},show:function(){va(this.div,{display:""})},destroy:function(){Aa(this.div);return null}};var Db=function(){};Db.prototype={init:function(a,b){var c=this;c.series=a;c.applyOptions(b);return c},applyOptions:function(a){var b=this,c=b.series;if(typeof a=="number"||a===null)b.y=a;else if(typeof a==
"object"&&typeof a.length!="number"){I(b,a);b.options=a}else if(typeof a[0]=="string"){b.name=a[0];b.y=a[1]}else if(typeof a[0]=="number"){b.x=a[0];b.y=a[1]}if(b.x===ia)b.x=c.autoIncrement()},select:function(a,b){var c=this,d=c.series,e=d.chart,f,g,h=ua(c.stateLayer,d.singlePointLayer,e.singlePointLayer);c.selected=a=ua(a,!c.selected);d.isDirty=true;c.firePointEvent(a?"select":"unselect");h&&h.clear();o(e.series,function(j){f=j.stateLayers;b||o(j.data,function(m){if(m.selected&&m!=c){m.selected=false;
ja(m,"unselect");j.isDirty=true}});if(j.isDirty){for(g in f)f[g].clear();j.render()}})},update:function(a,b){var c=this,d=c.series;b=ua(b,true);c.firePointEvent("update",{options:a},function(){c.applyOptions(a);d.isDirty=true;b&&d.chart.redraw()})},remove:function(a){var b=this,c=b.series,d=c.chart,e=c.data;a=ua(a,true);b.firePointEvent("remove",null,function(){o(e,function(f,g){f==b&&e.splice(g,1)});if(b.layer)b.layer=b.layer.destroy();if(b.legendItem){Aa(b.legendItem);b.legendItem=null;d.isDirty=
true}c.isDirty=true;a&&d.redraw()})},firePointEvent:function(a,b,c){var d=this,e=this.series;e=e.options;if(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])this.importEvents();if(a=="click"&&e.allowPointSelect)c=function(f){d.select(null,f.ctrlKey||f.metaKey||f.shiftKey)};ja(this,a,b,c)},importEvents:function(){if(!this.hasImportedEvents){var a=this,b=V(a.series.options.point,a.options);b=b.events;var c;a.events=b;for(c in b)Ma(a,c,b[c]);this.hasImportedEvents=true}},setTooltipText:function(){var a=
this;a.tooltipText=a.series.chart.options.tooltip.formatter.call({series:a.series,point:a,x:a.category,y:a.y,percentage:a.percentage})}};var Ga=function(){this.isCartesian=true;this.type="line";this.pointClass=Db};Ga.prototype={init:function(a,b){var c=this,d,e=a.series.length;c.chart=a;b=c.setOptions(b);I(c,{index:e,options:b,name:b.name||"Series "+(e+1),state:"",visible:b.visible!==false,selected:b.selected==true});a=b.events;for(d in a)Ma(c,d,a[d]);c.getColor();c.getSymbol();c.getData(b)},getData:function(a){var b=
this,c=b.chart,d="series"+cc++;if(!a.data&&a.dataURL){c.addLoading(d);nc(a.dataURL,function(e){b.dataLoaded(e);c.clearLoading(d)})}else b.dataLoaded(a.data)},dataLoaded:function(a){var b=this,c=b.chart,d=b.options,e=[""],f=d.dataParser,g={},h;if(d.dataURL&&!f)f=function(j){return eval(j)};if(f)a=f.call(b,a);b.layerGroup=h=new ma("series-group",c.plotLayer.div,null,{zIndex:2});d.states.hover.enabled&&e.push("hover");o(e,function(j){g[j]=new ma("state-"+j,h.div)});b.stateLayers=g;b.setData(a,false)},
autoIncrement:function(){var a=this,b=a.options,c=a.xIncrement;c=ua(c,b.pointStart,0);a.pointInterval=ua(a.pointInterval,b.pointInterval,1);a.xIncrement=c+a.pointInterval;return c},cleanData:function(){var a=this;a=a.data;var b;a.sort(function(c,d){return c.x-d.x});for(b=a.length-1;b>=0;b--)a[b-1]&&a[b-1].x==a[b].x&&a.splice(b-1,1)},getSegments:function(){var a=-1,b=[],c=this.data;o(c,function(d,e){if(d.y===null){e>a+1&&b.push(c.slice(a+1,e));a=e}else e==c.length-1&&b.push(c.slice(a+1,e+1))});this.segments=
b},setOptions:function(a){var b=this.chart.options.plotOptions;a=V(b[this.type],b.series,a);b=a.marker;var c=a.states.hover.marker;if(c.lineWidth===ia)c.lineWidth=b.lineWidth+1;if(c.radius===ia)c.radius=b.radius+1;return a},getColor:function(){var a=this.chart.options.colors;this.color=this.options.color||a[sb++]||"#0000ff";if(sb>=a.length)sb=0},getSymbol:function(){var a=this.chart.options.symbols,b=this.options.marker.symbol||"auto";if(b=="auto")b=a[Xb++];this.symbol=b;if(Xb>=a.length)Xb=0},addPoint:function(a,
b,c){var d=this,e=d.data;a=(new Db).init(d,a);b=ua(b,true);e.push(a);c&&e.shift();d.isDirty=true;b&&d.chart.redraw()},setData:function(a,b){var c=this;c.xIncrement=null;a=jb($b(a),function(d){return(new c.pointClass).init(c,d)});c.data=a;c.cleanData();c.getSegments();c.isDirty=true;ua(b,true)&&c.chart.redraw()},remove:function(a){var b=this,c=b.chart;a=ua(a,true);if(!b.isRemoving){b.isRemoving=true;ja(b,"remove",null,function(){Aa(b.layerGroup.div);o(b.areas,function(d){Aa(d)});Aa(b.legendItem);b.legendItem=
null;o(c.series,function(d,e){d==b&&c.series.splice(e,1)});c.isDirty=true;a&&c.redraw()})}b.isRemoving=false},redraw:function(){var a=this;a.translate();a.setTooltipPoints(true);a.chart.options.tooltip.enabled&&a.createArea();a.clear();a.render()},translate:function(){var a=this.chart,b=this,c=b.options.stacking,d=b.xAxis.categories,e=b.yAxis,f=e.stacks[b.type];o(this.data,function(g){var h=g.x,j=g.y,m;g.plotX=b.xAxis.translate(g.x);if(c){m=f[h];h=m.total;m.cum=m=m.cum-j;j=m+j;if(c=="percent"){m=
h?m*100/h:0;j=h?j*100/h:0}g.percentage=h?g.y*100/h:0;g.stackTotal=h;g.yBottom=e.translate(m,0,1)}if(j!==null)g.plotY=e.translate(j,0,1);g.clientX=a.inverted?a.plotHeight-g.plotX+a.plotTop:g.plotX+a.plotLeft;g.category=d&&d[g.x]!==ia?d[g.x]:g.x})},setTooltipPoints:function(a){var b=this,c=b.chart,d=c.inverted,e=[],f=d?c.plotHeight:c.plotWidth,g,h,j=[];if(a)b.tooltipPoints=null;o(b.segments,function(m){e=e.concat(m)});if(b.xAxis.reversed)e=e.reverse();o(e,function(m,r){b.tooltipPoints||m.setTooltipText();
g=e[r-1]?e[r-1].high+1:0;for(h=m.high=e[r+1]?Ra((m.plotX+(e[r+1]?e[r+1].plotX:f))/2):f;g<=h;)j[d?f-g++:g++]=m});b.tooltipPoints=j},drawLine:function(a){var b=this,c=b.options,d=b.chart,e=c.animation&&b.animate,f=b.stateLayers[a],g=c.lineColor||b.color,h=c.fillColor=="auto"?oc(b.color).setOpacity(c.fillOpacity||0.75).get():c.fillColor,j=d.inverted,m=(j?0:d.plotHeight)-b.yAxis.translate(0);if(a)c=V(c,c.states[a]);e&&b.animate(true);o(b.segments,function(r){var v=[],u=[];o(r,function(B){v.push(j?d.plotWidth-
B.plotY:B.plotX,j?d.plotHeight-B.plotX:B.plotY)});if(/area/.test(b.type)){for(var A=0;A<v.length;A++)u.push(v[A]);if(c.stacking&&b.type!="areaspline")for(A=r.length-1;A>=0;A--)u.push(r[A].plotX,r[A].yBottom);else u.push(j?m:r[r.length-1].plotX,j?r[0].plotX:m,j?m:r[0].plotX,j?r[r.length-1].plotX:m);f.drawPolyLine(u,null,null,c.shadow,h)}c.lineWidth&&f.drawPolyLine(v,g,c.lineWidth,c.shadow)});e&&b.animate()},animate:function(a){var b=this,c=b.chart,d=c.inverted,e=b.layerGroup.div;if(b.visible)if(a)va(e,
I({overflow:Ta},d?{height:0}:{width:0}));else{ub(e,d?{height:c.plotHeight+F}:{width:c.plotWidth+F},{duration:1E3});this.animate=null}},drawPoints:function(a){var b=this,c=b.stateLayers[a];a=b.options;var d=a.marker;a=b.data;var e=b.chart,f=e.inverted;d.enabled&&o(a,function(g){if(g.plotY!==ia)b.drawMarker(c,f?e.plotWidth-g.plotY:g.plotX,f?e.plotHeight-g.plotX:g.plotY,V(d,g.marker));g.selected&&b.drawPointState(g,"select",c)})},drawMarker:function(a,b,c,d){if(d.lineColor=="auto")d.lineColor=this.color;
if(d.fillColor=="auto")d.fillColor=this.color;if(d.symbol=="auto")d.symbol=this.symbol;a.drawSymbol(d.symbol,b,c,d.radius,d.lineWidth,d.lineColor,d.fillColor)},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a=this,b,c,d=a.data,e=a.options.dataLabels,f,g,h=a.chart,j=h.inverted,m=a.type,r=m=="pie",v;a.dataLabelsLayer=g=new ma("data-labels",a.layerGroup.div,null,{zIndex:1});e.style.color=e.color=="auto"?a.color:e.color;o(d,function(u){var A=u.plotX,B=u.plotY,S=u.tooltipPos;f=e.formatter.call({x:u.x,
y:u.y,series:a,point:u});b=(j?h.plotWidth-B:A)+e.x;c=(j?h.plotHeight-A:B)+e.y;if(S){b=S[0]+e.x;c=S[1]+e.y}if(r){if(!u.dataLabelsLayer)u.dataLabelsLayer=new ma("data-labels",u.layer.div,null,{zIndex:3});g=u.dataLabelsLayer}v=e.align;if(m=="column")b+={center:u.w/2,right:u.w}[v]||0;if(f)g[r?"drawText":"addText"](f,b,c,e.style,e.rotation,v)});r||g.strokeText()}},drawPointState:function(a,b,c){var d=this.chart,e=d.inverted,f=b=="hover";c=c||d.singlePointLayer;var g=this.options;if(f){if(!c)c=d.singlePointLayer=
new ma("single-point",d.plotLayer.div,null,{zIndex:3});c.clear()}if(b){var h=g.states[b].marker;b=g.marker.states[b];if(f&&b.radius===ia)b.radius=h.radius+2;if((f=V(g.marker,a.marker,h,b))&&f.enabled)this.drawMarker(c,e?d.plotWidth-a.plotY:a.plotX,e?d.plotHeight-a.plotX:a.plotY,f)}},render:function(){var a=this,b,c=a.stateLayers;a.drawDataLabels();if(a.visible)for(b in c){a.drawLine(b);a.drawPoints(b)}else a.setVisible(false,false);if(!a.hasRendered&&c.hover){c.hover.hide();hasRendered=true}a.isDirty=
false},clear:function(){var a=this.stateLayers;for(var b in a){a[b].clear();a[b].cleared=true}if(this.dataLabelsLayer){this.dataLabelsLayer.clear();this.hasDrawnDataLabels=false}},setState:function(a){a=a||"";if(this.state!=a){var b=this,c=b.stateLayers,d=c[a];c=c[b.state];var e=b.singlePointLayer||b.chart.singlePointLayer;b.state=a;if(d)if(a)d.show();else{c&&c.hide();e&&e.clear()}}},setVisible:function(a,b){var c=this,d=c.chart,e=c.layerGroup,f=c.legendItem,g=c.areas,h=c.visible;(c.visible=a=a===
ia?!h:a)?e.show():e.hide();if(f){f.className=a?"":Cb;d.legend.drawGraphics(true)}g&&o(g,function(j){a?d.tracker.insertAtFront(j):Aa(j)});if(d.options.chart.ignoreHiddenSeries){c.options.stacking&&o(d.series,function(j){if(j.options.stacking&&j.visible)j.isDirty=true});b!==false&&d.redraw()}ja(c,a?"show":"hide")},show:function(){this.setVisible(true)},hide:function(){this.setVisible(false)},select:function(a){var b=this;b.selected=a=a===ia?!b.selected:a;if(b.checkbox)b.checkbox.checked=a;ja(b,a?"select":
"unselect")},getAreaCoords:function(){var a=this,b=this.chart,c=b.inverted,d=b.plotWidth,e=b.plotHeight,f=b.options.tooltip.snap,g=[];o(a.splinedata||a.segments,function(h,j){if(h.length>1&&h[0].x>h[1].x)h=reverseArray(h);var m=[],r=[],v=[];o([r,v],function(u){for(var A=0,B=0,S,na,ra=[h[0]],yb=u==r?1:-1,hb,$a,fb,z,O,L,Va;h[B];){if(h[B].plotX>h[A].plotX+f||B==h.length-1){S=h[B];na=h.slice(A,B-1);o(na,function(Sa){if(yb*Sa.plotY<yb*S.plotY)S=Sa});if(N(h[A].plotX)<N(S.plotX)||h[B].plotX>h[A].plotX+f)ra.push(S);
A=B}B++}ra[ra.length-1]!=h[h.length-1]&&ra.push(h[h.length-1]);for(B=0;B<ra.length;B++)if(B>0){$a=ra[B].plotX;hb=ra[B].plotY;A=ra[B-1].plotX;na=ra[B-1].plotY;z=$a-ra[B-1].plotX;L=O=hb-ra[B-1].plotY;fb=-z;Va=wa.sqrt(wa.pow(L,2)+wa.pow(fb,2));if(B==1){A-=f/Va*z;na-=f/Va*O}else if(B==ra.length-1){$a+=f/Va*z;hb+=f/Va*O}z=yb*f/Va;A=N(A+z*L);na=N(na+z*fb);$a=N($a+z*L);fb=N(hb+z*fb);if(u[u.length-1]&&u[u.length-1][0]>A)for(hb=false;!hb;){O=u.pop();L=u[u.length-1];if(!L)break;z=(na-fb)/(A-$a);O=(L[1]-O[1])/
(L[0]-O[0]);O=(-O*L[0]+L[1]+z*A-na)/(z-O);z=z*(O-A)+na;if(O>L[0]){u.push([N(O),N(z),1]);hb=true}}else isNaN(A)||u.push([A,na]);u[u.length-1]&&u[u.length-1][0]<$a&&u.push([$a,fb])}});for(j=0;j<r.length;j++)m.push(c?d-r[j][1]:r[j][0],c?e-r[j][0]:r[j][1]);for(j=v.length-1;j>=0;j--)m.push(c?d-v[j][1]:v[j][0],c?e-v[j][0]:v[j][1]);!m.length&&h[0]&&m.push(N(h[0].plotX),N(h[0].plotY));g.push([m.join(",")])});return g},createArea:function(){if(this.options.enableMouseTracking!==false){var a,b=this,c=b.options,
d=b.chart,e=d.tracker,f=b.getAreaCoords(),g=[],h=b.areas,j;h&&o(h,function(m){Aa(m)});o(f,function(m){j=/^[0-9]+,[0-9]+$/.test(m[0]);a=R("area",{shape:j?"circle":"poly",chart:d,coords:m[0]+(j?","+d.options.tooltip.snap:""),onmouseover:function(){if(!(!b.visible||d.mouseIsDown)){var r=d.hoverSeries;d.hoverPoint=m[1];c.events.mouseOver&&ja(b,"mouseOver",{point:d.hoverPoint});r&&r!=b&&r.setState();/(column|bar|pie)/.test(b.type)||e.insertAtFront(a);b.setState("hover");d.hoverSeries=b}},onmouseout:function(){var r=
d.hoverSeries;r&&c.events.mouseOut&&ja(r,"mouseOut")}});if(c.cursor=="pointer")a.href="javascript:;";e.insertAtFront(a);g.push(a)});b.areas=g}}};var Nc=db(Ga),Oc=db(Ga,{type:"area"}),Bc=db(Ga,{type:"spline",translate:function(){var a=this;Ga.prototype.translate.apply(a,arguments);a.splinedata=a.getSplineData()},drawLine:function(){var a=this,b=a.segments;a.segments=a.splinedata;Ga.prototype.drawLine.apply(a,arguments);a.segments=b},getSplineData:function(){var a=this,b=a.chart,c=[],d;o(a.segments,
function(e){if(a.xAxis.reversed)e=e.reverse();var f=[],g,h;o(e,function(j,m){g=e[m+2]||e[m+1]||j;h=e[m-2]||e[m-1]||j;g.plotX>0&&h.plotY<b.plotWidth&&f.push(j)});if(f.length>1)d=N(fc(b.plotWidth,f[f.length-1].clientX-f[0].clientX)/3);c.push(e.length>1?d?(new Cc(f)).get(d):[]:e)});return a.splinedata=c}});Cc.prototype={get:function(a){a||(a=50);var b=this.n;b=(this.xdata[b-1]-this.xdata[0])/(a-1);var c=[],d=[];c[0]=this.xdata[0];d[0]=this.ydata[0];for(var e=[{plotX:c[0],plotY:d[0]}],f=1;f<a;f++){c[f]=
c[0]+f*b;d[f]=this.interpolate(c[f]);e[f]={plotX:c[f],plotY:d[f]}}return e},interpolate:function(a){for(var b=this.n-1,c=0;b-c>1;){var d=(b+c)/2;if(this.xdata[Ra(d)]>a)b=d;else c=d}b=Ra(b);c=Ra(c);d=this.xdata[b]-this.xdata[c];var e=(this.xdata[b]-a)/d;a=(a-this.xdata[c])/d;return e*this.ydata[c]+a*this.ydata[b]+((e*e*e-e)*this.y2[c]+(a*a*a-a)*this.y2[b])*d*d/6}};var Pc=db(Bc,{type:"areaspline"}),Lb=db(Ga,{type:"column",init:function(){Ga.prototype.init.apply(this,arguments);var a=this,b=a.chart;
b.hasRendered&&o(b.series,function(c){if(c.type==a.type)c.isDirty=true})},translate:function(){var a=this,b=a.chart,c=0,d;Ga.prototype.translate.apply(a);o(b.series,function(S){if(S.type==a.type)if(S.options.stacking){bb(d)||(d=c++);S.columnIndex=d}else S.columnIndex=c++});var e=a.options,f=a.data,g=b.inverted,h=b.plotWidth,j=b.plotHeight,m=a.closestPoints;m=Ia(f[1]?f[m].plotX-f[m-1].plotX:g?j:h);var r=m*e.groupPadding,v=m-2*r;v=v/c;e=v*e.pointPadding;var u=v-2*e;b=(b.options.xAxis.reversed?c-a.columnIndex:
a.columnIndex)||0;var A=-(m/2)+r+b*v+e,B=a.yAxis.translate(0);o(f,function(S){S.plotX+=A;S.w=u;S.y0=(g?h:j)-B;S.h=(S.yBottom||S.y0)-S.plotY})},drawLine:function(){},getSymbol:function(){},drawPoints:function(a){var b=this,c=b.options,d=b.chart,e=c.animation&&b.animate,f=d.inverted,g=b.data,h=b.stateLayers[a];e&&this.animate(true);o(g,function(j){if(j.plotY!==ia)h.drawRect(f?d.plotWidth-j.plotY-j.h:j.plotX,f?d.plotHeight-j.plotX-j.w:j.h>=0?j.plotY:j.plotY+j.h,f?j.h:j.w,f?j.w:Ia(j.h),c.borderColor,
c.borderWidth,c.borderRadius,j.color||b.color,c.shadow);j.selected&&b.drawPointState(j,"select",h)});e&&b.animate()},drawPointState:function(a,b,c){var d=this,e=d.chart,f=d.options,g=a?a.options:null,h=e.inverted;c=c||d.singlePointLayer;if(b=="hover"){if(!c)c=d.singlePointLayer=new ma("single-point",d.layerGroup.div);c.clear()}if(b&&this.options.states[b]){b=V(f,f.states[b],g);c.drawRect(h?e.plotWidth-a.plotY-a.h:a.plotX,h?e.plotHeight-a.plotX-a.w:a.plotY,h?a.h:a.w,h?a.w:a.h,b.borderColor,b.borderWidth,
b.borderRadius,oc(b.color||this.color).brighten(b.brightness).get(),b.shadow)}},getAreaCoords:function(){var a=[],b=this.chart,c=b.inverted;o(this.data,function(d){var e=fc(Ia(d.h),3)*(d.h<0?-1:1),f=c?b.plotWidth-d.plotY-e:d.plotX,g=c?b.plotHeight-d.plotX-d.w:d.plotY,h=g+(c?d.w:e);e=f+(c?e:d.w);if(!c&&e-f<1)e=f+1;else if(c&&g-h<1)g=h+1;a.push([jb([f,h,f,g,e,g,e,h],N).join(","),d])});return a},cleanData:function(){var a=this,b=a.data,c,d,e,f;Ga.prototype.cleanData.apply(a);for(f=b.length-1;f>=0;f--)if(b[f-
1]){c=b[f].x-b[f-1].x;if(d===ia||c<d){d=c;e=f}}a.closestPoints=e},animate:function(a){var b=this,c=b.chart,d=c.inverted,e=b.layerGroup.div;if(a)e.style[d?"left":"top"]=(d?-c.plotWidth:c.plotHeight)+F;else{ub(e,c.inverted?{left:0}:{top:0});b.animate=null}},remove:function(){var a=this,b=a.chart;b.hasRendered&&o(b.series,function(c){if(c.type==a.type)c.isDirty=true});Ga.prototype.remove.apply(a,arguments)}}),qc=db(Lb,{type:"bar",init:function(a){a.inverted=this.inverted=true;Lb.prototype.init.apply(this,
arguments)}}),Rc=db(Ga,{type:"scatter",getAreaCoords:function(){var a=this.data,b=[];o(a,function(c){b.push([[N(c.plotX),N(c.plotY)].join(","),c])});return b},cleanData:function(){}});P=db(Db,{setState:function(a){this.series.drawPointState(this,a)},init:function(){Db.prototype.init.apply(this,arguments);var a=this,b=a.series,c=b.chart.options.colors;I(a,{visible:a.visible!==false,name:ua(a.name,"Slice"),color:a.color||c[sb++]});if(sb>=c.length)sb=0;if(!a.layer)a.layer=new ma("pie",b.layerGroup.div);
b=function(){a.slice()};Ma(a,"select",b);Ma(a,"unselect",b);return a},setVisible:function(a){var b=this,c=b.layer,d=b.legendItem;(b.visible=a=a===ia?!b.visible:a)?c.show():c.hide();if(d){d.className=a?"":Cb;b.series.chart.legend.drawGraphics(true)}},slice:function(a,b){var c=this,d=c.series;b=ua(b,true);c.sliced=bb(a)?a:!c.sliced;d.isDirty=true;b&&d.chart.redraw()}});var Qc=db(Ga,{type:"pie",isCartesian:false,pointClass:P,getColor:function(){},translate:function(){var a=0,b=this,c=-0.25,d=b.options,
e=d.slicedOffset,f=d.center,g=b.chart;b=b.data;var h=2*wa.PI,j;f.push(d.size);f=jb(f,function(m,r){return/%$/.test(m)?g["plot"+(r?"Height":"Width")]*parseInt(m)/100:m});o(b,function(m){a+=m.y});o(b,function(m){j=a?m.y/a:0;m.start=c*h;c+=j;m.end=c*h;m.percentage=j*100;m.center=[f[0],f[1]];m.size=f[2];var r=(m.end+m.start)/2;m.centerSliced=jb([Yb(r)*e+f[0],Zb(r)*e+f[1]],N)});this.setTooltipPoints()},render:function(){this.drawPoints();this.drawDataLabels()},drawPoints:function(){var a=this;o(this.data,
function(b){a.drawPoint(b,b.layer.getCtx(),b.color);b.selected&&a.drawPointState(b,"select",b.layer)})},getSymbol:function(){},drawPointState:function(a,b,c){var d=this,e=d.options;if(a){c=c||a.stateLayer;if(b=="hover"){if(!c)c=a.stateLayer=new ma("single-point",a.layer.div);c.clear()}if(b&&d.options.states[b]){b=V(e,e.states[b]);this.drawPoint(a,c.getCtx(),b.color||a.color,b.brightness)}}d.hoverPoint&&d.hoverPoint.stateLayer.clear();d.hoverPoint=a},drawPoint:function(a,b,c,d){var e=this.options,
f=a.sliced?a.centerSliced:a.center,g=f[0];f=f[1];var h=a.size,j=Ha&&a.percentage==100?a.start:a.end;if(a.y>0){b.fillStyle=oc(c).brighten(d).get(b);b.strokeStyle=e.borderColor;b.lineWidth=e.borderWidth;b.beginPath();b.moveTo(g,f);b.arc(g,f,h/2,a.start,j,false);b.lineTo(g,f);b.closePath();b.fill();b.stroke()}},getAreaCoords:function(){var a=[];o(this.data,function(b){for(var c=b.center[0],d=b.center[1],e=b.size/2,f=b.start,g=b.end,h=[],j=f;j;j+=0.25){if(j>=g)j=g;h=h.concat([c+Yb(j)*e,d+Zb(j)*e]);if(j>=
g)break}h=h.concat([c,d]);b.tooltipPos=[c+2*Yb((f+g)/2)*e/3,d+2*Zb((f+g)/2)*e/3];a.push([jb(h,N).join(","),b])});return a},clear:function(){o(this.data,function(a){a.layer.clear();a.dataLabelsLayer&&a.dataLabelsLayer.clear();a.stateLayer&&a.stateLayer.clear()})}});Highcharts={numberFormat:Fc,dateFormat:pc,setOptions:Ec,Chart:Gc}})();
