package br.ufrn.sigaa.ensino.tecnico.dominio;

// Generated 13/09/2006 08:49:22 by Hibernate Tools 3.1.0.beta5

import java.util.Collection;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ufrn.arq.dominio.PersistDB;
import br.ufrn.arq.dominio.RegistroEntrada;
import br.ufrn.arq.seguranca.log.AtualizadoEm;
import br.ufrn.arq.seguranca.log.AtualizadoPor;
import br.ufrn.arq.seguranca.log.CriadoEm;
import br.ufrn.arq.seguranca.log.CriadoPor;
import br.ufrn.arq.util.EqualsUtil;
import br.ufrn.arq.util.HashCodeUtil;
import br.ufrn.sigaa.ensino.dominio.ComponenteCurricular;

/**
 * Relacionamento entre DISCIPLINA  e ESTRUTURA CURRICULAR
 * DisciplinaComplementar generated by hbm2java
 */
@Entity
@Table(name = "disciplina_complementar", schema = "tecnico", uniqueConstraints = {})
public class DisciplinaComplementar implements PersistDB {

	/** Chave primária */
	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id_disciplina_complementar", unique = true, nullable = false, insertable = true, updatable = true)
	private int id;

	/** Indica o Componente Curricular Associado. */
	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_disciplina", unique = false, nullable = false, insertable = true, updatable = true)
	private ComponenteCurricular disciplina;

	/** Indica a Estrutura Curricular associada. */
	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estrutura_curricular", unique = false, nullable = true, insertable = true, updatable = true)
	private EstruturaCurricularTecnica estruturaCurricularTecnica;

	/** Indica o período que a Disciplina será ofertada na Estrutura Curricular em questão. */
	@Column(name = "periodo_oferta", unique = false, nullable = true, insertable = true, updatable = true)
	private Integer periodoOferta;
	
	/** Data de cadastro da Disciplina Complementar. */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_cadastro")
	@CriadoEm
	private Date dataCadastro;

	/** Registro entrada do usuário que cadastrou. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_registro_cadastro")
	@CriadoPor
	private RegistroEntrada registroCadastro;

	/** Data da última atualização da Disciplina Complementar. */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="data_atualizacao")
	@AtualizadoEm
	private Date dataAtualizacao;

	/** Registro entrada do usuário que realizou a última atualização. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_registro_atualizacao")
	@AtualizadoPor
	private RegistroEntrada registroAtualizacao;

	// Constructors

	/** default constructor */
	public DisciplinaComplementar() {
	}

	/** default minimal constructor */
	public DisciplinaComplementar(int id) {
		this.id = id;
	}

	/** minimal constructor */
	public DisciplinaComplementar(int idDisciplinaComplementar,
			ComponenteCurricular disciplina) {
		this.id = idDisciplinaComplementar;
		this.disciplina = disciplina;
	}

	/** full constructor */
	public DisciplinaComplementar(int idDisciplinaComplementar, Modulo modulo,
			ComponenteCurricular disciplina,
			EstruturaCurricularTecnica estruturaCurricularTecnica,
			boolean obrigatoria, Integer periodoOferta) {
		this.id = idDisciplinaComplementar;
		this.disciplina = disciplina;
		this.estruturaCurricularTecnica = estruturaCurricularTecnica;
		this.periodoOferta = periodoOferta;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int idDisciplinaComplementar) {
		this.id = idDisciplinaComplementar;
	}

	public ComponenteCurricular getDisciplina() {
		return this.disciplina;
	}

	public void setDisciplina(ComponenteCurricular disciplina) {
		this.disciplina = disciplina;
	}

	public EstruturaCurricularTecnica getEstruturaCurricularTecnica() {
		return this.estruturaCurricularTecnica;
	}

	public void setEstruturaCurricularTecnica(
			EstruturaCurricularTecnica estruturaCurricularTecnica) {
		this.estruturaCurricularTecnica = estruturaCurricularTecnica;
	}

	public Integer getPeriodoOferta() {
		return this.periodoOferta;
	}

	public void setPeriodoOferta(Integer periodoOferta) {
		this.periodoOferta = periodoOferta;
	}

	public Date getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public RegistroEntrada getRegistroCadastro() {
		return registroCadastro;
	}

	public void setRegistroCadastro(RegistroEntrada registroCadastro) {
		this.registroCadastro = registroCadastro;
	}

	public Date getDataAtualizacao() {
		return dataAtualizacao;
	}

	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	public RegistroEntrada getRegistroAtualizacao() {
		return registroAtualizacao;
	}

	public void setRegistroAtualizacao(RegistroEntrada registroAtualizacao) {
		this.registroAtualizacao = registroAtualizacao;
	}

	/**
	 * Compara se o id passado está presenta no Coleção.
	 */
	public static boolean compareTo(int id, Collection<DisciplinaComplementar> disciplinaCompl) {
		for (DisciplinaComplementar disc : disciplinaCompl) {
			if ( disc.getId() == id )
				return false;
		}
		return true;
	}
	
	@Override
	public boolean equals(Object obj) {
		return EqualsUtil.testEquals(this, obj, "id", "disciplina");
	}

	@Override
	public int hashCode() {
		return HashCodeUtil.hashAll(id, disciplina);
	}

}
